/* Maadoo Job · js/data.js — fictional sample data (companies, jobs, mentors, board, quiz) + career-map data. Classic script sharing one global scope; see CLAUDE.md for load order. */
/* ---------- data (fictional) ---------- */
const NAV=[
 {id:'home',t:['หน้าแรก','Home'],i:'<path d="M3 11l9-7 9 7v9a1 1 0 0 1-1 1h-5v-6h-6v6H4a1 1 0 0 1-1-1z"/>'},
 {id:'explore',t:['บริษัท','Companies'],i:'<circle cx="11" cy="11" r="7"/><path d="M20 20l-4-4"/>'},
 {id:'jobs',t:['งาน','Jobs'],i:'<rect x="3" y="7" width="18" height="13" rx="3"/><path d="M9 7V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2M3 13h18"/>'},
 {id:'write',t:['เขียนรีวิว','Write'],i:'<path d="M12 5v14M5 12h14"/>'},
 {id:'ask',t:['ปรึกษา','Ask'],i:'<path d="M4 5h16v11H9l-5 4z"/>'},
 {id:'me',t:['ฉัน','Me'],i:'<circle cx="12" cy="8" r="4"/><path d="M4 21c1.5-4 4.5-6 8-6s6.5 2 8 6"/>'},
];
const JOBS=[
 {id:'j1',co:'cloudbun',title:['นักศึกษาฝึกงาน Data Analyst','Data Analyst Intern'],type:'intern',pay:[400,500],unit:'day',tags:[['ไฮบริด','Hybrid'],['Python','Python']],days:2,spon:true},
 {id:'j2',co:'biofresh',title:['นักศึกษาฝึกงาน QC จุลชีววิทยา','QC Microbiology Intern'],type:'intern',pay:[350,350],unit:'day',tags:[['รถรับส่ง','Shuttle'],['ข้าวฟรี','Free lunch']],days:1,spon:false},
 {id:'j3',co:'northstar',title:['QC Microbiologist','QC Microbiologist'],type:'full',pay:[25000,32000],unit:'month',tags:[['GMP','GMP'],['โบนัส 3 เดือน','3-month bonus']],days:5,spon:true},
 {id:'j4',co:'greencap',title:['Fermentation Technician','Fermentation Technician'],type:'full',pay:[19000,24000],unit:'month',tags:[['หอพักฟรี','Free dorm'],['ทีมเล็ก','Small team']],days:3,spon:false},
 {id:'j5',co:'siamlab',title:['Lab Analyst (จบใหม่)','Lab Analyst (new grad)'],type:'full',pay:[17000,20000],unit:'month',tags:[['ISO 17025','ISO 17025'],['ใกล้ MRT','Near MRT']],days:6,spon:false},
 {id:'j6',co:'siamlab',title:['นักศึกษาฝึกงานแล็บจุลชีวะ','Microbiology Lab Intern'],type:'intern',pay:[0,0],unit:'day',tags:[['PCR','PCR'],['ได้ลงมือจริง','Hands-on']],days:9,spon:false},
 {id:'j7',co:'megamart',title:['QA อาหารสด','Fresh Food QA'],type:'full',pay:[22000,27000],unit:'month',tags:[['ส่วนลดพนักงาน','Staff discount']],days:4,spon:false},
 {id:'j8',co:'biofresh',title:['R&D Food Scientist','R&D Food Scientist'],type:'full',pay:[28000,36000],unit:'month',tags:[['ของออกขายจริง','Products hit shelves']],days:12,spon:false},
 {id:'j9',co:'srisiam',title:['Management Trainee 2027','Management Trainee 2027'],type:'full',pay:[35000,35000],unit:'month',tags:[['หมุนงาน 4 ฝ่าย','4 rotations'],['โบนัสสูง','High bonus']],days:3,spon:true},
 {id:'j10',co:'wellness',title:['นักศึกษาฝึกงานจุลชีวะคลินิก','Clinical Microbiology Intern'],type:'intern',pay:[300,300],unit:'day',tags:[['AST','AST'],['ใกล้ MRT','Near MRT']],days:2,spon:false},
 {id:'j11',co:'speedflow',title:['Supply Chain Analyst','Supply Chain Analyst'],type:'full',pay:[26000,32000],unit:'month',tags:[['Excel','Excel'],['Power BI','Power BI']],days:6,spon:false},
 {id:'j12',co:'riverlight',title:['F&B Hygiene Officer','F&B Hygiene Officer'],type:'full',pay:[21000,25000],unit:'month',tags:[['Service charge','Service charge'],['ใช้ภาษาอังกฤษ','English']],days:8,spon:false},
 {id:'j13',co:'thaimotor',title:['Environmental Officer','Environmental Officer'],type:'full',pay:[25000,30000],unit:'month',tags:[['บำบัดน้ำเสีย','Wastewater'],['หอพักฟรี','Free dorm']],days:4,spon:false},
 {id:'j14',co:'popcorn',title:['นักศึกษาฝึกงาน Content Creator','Content Creator Intern'],type:'intern',pay:[0,0],unit:'day',tags:[['TikTok','TikTok'],['ลงพอร์ตได้','Portfolio work']],days:1,spon:false},
 {id:'j15',co:'pixelchang',title:['QA Tester (เกม)','Game QA Tester'],type:'full',pay:[18000,22000],unit:'month',tags:[['ไฮบริด','Hybrid'],['รักเกม','Love games']],days:5,spon:true},
 {id:'j16',co:'sunwave',title:['Biogas Process Engineer','Biogas Process Engineer'],type:'full',pay:[32000,40000],unit:'month',tags:[['พลังงานสะอาด','Clean energy'],['โบนัส 5 เดือน','5-month bonus']],days:10,spon:false},
 {id:'j17',co:'bloomy',title:['นักศึกษาฝึกงาน Cosmetic QC','Cosmetic QC Intern'],type:'intern',pay:[350,350],unit:'day',tags:[['Challenge test','Challenge test'],['ส่วนลดสินค้า','Product discount']],days:2,spon:false},
 {id:'j18',co:'puimek',title:['นักศึกษาฝึกงาน Ground Staff','Ground Staff Intern'],type:'intern',pay:[350,350],unit:'day',tags:[['ใช้ภาษาอังกฤษ','English'],['ส่วนลดตั๋ว','Ticket discount']],days:3,spon:false},
];
const TOPICS={intern:['ฝึกงาน','Internships'],resume:['เรซูเม่ & สัมภาษณ์','Resume & interviews'],salary:['เงินเดือน','Salary'],switch:['ย้ายสาย','Career switch'],rights:['สิทธิแรงงาน','Labor rights']};
const MENTORS=[
 {id:'m1',fac:'agro',roles:['qa'],name:['พี่มิ้นท์','Mint'],role:['QA Officer · 4 ปี','QA Officer · 4 yrs'],at:['ไบโอเฟรช ฟู้ดส์','BioFresh Foods'],ava:'🧪',bg:'#FFE08A',n:86,price:129,top:['intern','resume'],tags:[['ฝึกงาน QC','QC internships'],['HACCP','HACCP'],['เรซูเม่','Resume']],bio:['เคยเป็นเด็กฝึกงานที่นี่มาก่อน ช่วยเตรียมตัวฝึกงานสายอาหารได้ทุกขั้นตอน','I started here as an intern. I can walk you through food-industry internships step by step.']},
 {id:'m2',fac:'agro',roles:['qcmicro'],name:['พี่ต้น','Ton'],role:['QC Microbiologist · 6 ปี','QC Microbiologist · 6 yrs'],at:['นอร์ธสตาร์ ฟาร์มา','Northstar Pharma'],ava:'💊',bg:'#C9DBFF',n:54,price:179,top:['salary','switch'],tags:[['สายยา','Pharma careers'],['ต่อรองเงินเดือน','Salary talks']],bio:['ย้ายจากสายอาหารมาสายยา เงินเดือนขึ้น 40% เล่าให้ฟังได้หมดว่าทำยังไง','Moved from food to pharma with a 40% raise. Happy to share exactly how.']},
 {id:'m3',fac:'sci',roles:['da'],name:['พี่แพร','Prae'],role:['Data Analyst · 3 ปี','Data Analyst · 3 yrs'],at:['คลาวด์บัน เทค','Cloudbun Tech'],ava:'📊',bg:'#FFD0BE',n:41,price:99,top:['switch','resume'],tags:[['ย้ายสายไป Data','Switching to data'],['ซ้อมสัมภาษณ์','Mock interviews']],bio:['จบวิทย์แต่ย้ายมาทำ Data ได้ในปีเดียว มีแผนเรียนให้ดูเลย','Science grad who moved into data within a year. I’ll share my study plan.']},
 {id:'m4',fac:'arts',roles:['hr'],name:['พี่โอม','Ohm'],role:['HR Business Partner · 8 ปี','HR Business Partner · 8 yrs'],at:['บริษัทค้าปลีก','Retail company'],ava:'🤝',bg:'#DDF0B5',n:120,price:249,top:['resume','rights','salary'],tags:[['ตรวจเรซูเม่','Resume review'],['สิทธิแรงงาน','Labor rights']],bio:['อ่านเรซูเม่มาแล้วกว่า 5,000 ฉบับ รู้ว่า HR มองหาอะไรใน 10 วินาทีแรก','I’ve read 5,000+ resumes and know what HR looks for in the first 10 seconds.']},
 {id:'m5',fac:'sci',roles:['ferm'],name:['พี่เฟิร์น','Fern'],role:['Fermentation Lead · 5 ปี','Fermentation Lead · 5 yrs'],at:['กรีนแคป บริวอรี่','Greencap Brewery'],ava:'🍺',bg:'#FFE3B8',n:33,price:149,top:['intern','switch'],tags:[['งานหมัก','Fermentation'],['สตาร์ทอัพเครื่องดื่ม','Drink startups']],bio:['ชอบงานหมักแต่ไม่รู้จะเริ่มตรงไหน? มาคุยกัน ตั้งแต่ฝึกงานถึงเปิดแบรนด์','Love fermentation but not sure where to start? From internships to launching a brand.']},
 {id:'m6',fac:'sci',roles:['qc'],name:['พี่บอส','Boss'],role:['Lab Supervisor · 7 ปี','Lab Supervisor · 7 yrs'],at:['สยามแล็บ อนาลิติกส์','Siam Lab Analytics'],ava:'🔬',bg:'#BDEBDD',n:72,price:199,top:['intern','rights'],tags:[['ISO 17025','ISO 17025'],['ชีวิตคนแล็บ','Lab life']],bio:['คุมแล็บมา 7 ปี ถามได้ทั้งเรื่องงาน OT และการรับมือหัวหน้า','7 years running a lab. Ask me about the work, overtime and handling bosses.']},
 {id:'m7',fac:'sci',roles:['uxui'],name:['พี่จูน','June'],role:['Product Designer · 4 ปี','Product Designer · 4 yrs'],at:['คลาวด์บัน เทค','Cloudbun Tech'],ava:'🎨',bg:'#FFD3E2',n:28,price:129,top:['switch','resume'],tags:[['พอร์ตโฟลิโอ','Portfolio'],['UX/UI','UX/UI']],bio:['จากนักศึกษาชีวะสู่ดีไซเนอร์ ช่วยทำพอร์ตให้ดูโปรได้','From biology student to designer. I’ll help your portfolio look pro.']},
 {id:'m8',fac:'comm',roles:['hr'],name:['พี่นัท','Nut'],role:['Recruiter · 5 ปี','Recruiter · 5 yrs'],at:['บริษัทจัดหางาน','Recruitment agency'],ava:'🎯',bg:'#D9D3FF',n:95,price:179,top:['salary','resume'],tags:[['ต่อรองเงินเดือน','Negotiation'],['หางานจบใหม่','First job hunt']],bio:['อยู่ฝั่งคนจ้างมาตลอด บอกได้ว่าควรขอเงินเดือนเท่าไหร่ถึงไม่ขาดทุน','I’ve always sat on the hiring side. I’ll tell you what to ask for.']},
 {id:'m9',fac:'agro',roles:['qa'],name:['พี่ฝน','Fon'],role:['QA Associate · 1 ปี','QA Associate · 1 yr'],at:['เมกะมาร์ท รีเทล','Megamart Retail'],ava:'🌱',bg:'#D4F2C4',n:3,price:89,top:['intern','switch'],tags:[['เพิ่งเริ่มงาน','Just started'],['QA อาหารสด','Fresh food QA']],bio:['เพิ่งจบมาปีเดียว ยังจำได้ทุกขั้นตอนตอนหางานแรก','Graduated a year ago and still remember every step of the first job hunt.']},
];
/* mentor reviews (fictional samples). The rating on every card is computed from these + real reviews, so it always matches. */
const MTAGS={direct:['ตรงประเด็น','To the point','ตรงประเด็น','To the point'],kind:['ใจดีเป็นกันเอง','Kind & friendly','ใจดี','Kind'],real:['ให้ข้อมูลจริง','Honest, real info','ข้อมูลจริง','Real info'],ontime:['ตรงเวลา','On time','ตรงเวลา','On time'],resume:['ช่วยเรื่องเรซูเม่','Resume help','ช่วยเรซูเม่','Resume help'],recommend:['แนะนำต่อได้','Would recommend','แนะนำต่อ','Recommend']};
const WHO={f4:['นักศึกษาปี 4 · สายอาหาร','Year 4 student · Food science'],f3:['นักศึกษาปี 3 · สายอาหาร','Year 3 student · Food science'],m4:['นักศึกษาปี 4 · จุลชีวะ','Year 4 student · Microbiology'],m2:['นักศึกษาปี 2 · จุลชีวะ','Year 2 student · Microbiology'],c4:['นักศึกษาปี 4 · เคมี','Year 4 student · Chemistry'],b3:['นักศึกษาปี 3 · บริหาร','Year 3 student · Business'],s4:['นักศึกษาปี 4 · สถิติ','Year 4 student · Statistics'],g1:['จบใหม่ 1 ปี · สายวิทย์','1 year after graduating · Science'],g0:['เพิ่งจบ · วิศวะ','New grad · Engineering'],d3:['นักศึกษาปี 3 · ออกแบบ','Year 3 student · Design'],p5:['นักศึกษาปี 5 · เภสัช','Year 5 student · Pharmacy']};
const MON={9:['ก.ย. 2026','Sep 2026'],8:['ส.ค. 2026','Aug 2026'],7:['ก.ค. 2026','Jul 2026'],6:['มิ.ย. 2026','Jun 2026'],5:['พ.ค. 2026','May 2026']};
const R=(s,tags,th,en,who,mo,reply)=>({s,tags,c:[th,en],who:WHO[who],d:MON[mo],reply:reply||null});
const MREV={
 m1:[R(5,['direct','resume'],'พี่ช่วยแก้เรซูเม่ฝึกงาน QC จนได้สัมภาษณ์ 2 ที่ในสัปดาห์เดียว','She fixed my QC internship resume and I got two interviews in one week','f4',9,['ดีใจด้วยนะ! ขอให้ได้ที่ที่ชอบเลย','So happy for you! Hope you land the one you like']),
  R(5,['kind','real'],'เล่าชีวิตฝึกงานจริง ๆ ไม่อวย ทำให้รู้ว่าต้องเตรียมอะไร','Told me what the internship is really like, no sugar-coating','f3',9),
  R(5,['direct','ontime'],'ตรงเวลา ตอบครบทุกคำถาม HACCP','On time and answered every HACCP question','m4',8),
  R(4,['kind'],'ใจดีมาก แต่อยากให้มีเวลามากกว่านี้','Very kind, I just wished we had more time','f3',8),
  R(5,['recommend','resume'],'คุ้มค่ามาก แนะนำเพื่อนไปอีก 2 คน','Totally worth it, I already sent two friends','f4',7)],
 m2:[R(5,['real','direct'],'เล่าตัวเลขเงินเดือนสายยาแบบละเอียด ช่วยตัดสินใจย้ายสายได้เลย','Walked me through real pharma salary numbers, helped me decide to switch','g1',9),
  R(5,['direct'],'ต่อรองเงินเดือนตามที่พี่สอน ได้เพิ่มมา 3,000','Used his negotiation tips and got 3,000 more','g1',8,['เก่งมาก! จำไว้ว่าเราขอได้เสมอ','Great job! Remember you can always ask']),
  R(4,['real','ontime'],'ข้อมูลแน่น แต่พูดเร็วไปนิด','Packed with info, just talked a bit fast','p5',8),
  R(5,['recommend'],'ถ้าจะเข้าสายยา ต้องคุยกับพี่ต้น','If you want pharma, talk to Ton','m4',7)],
 m3:[R(5,['direct','resume'],'ได้แผนเรียน Data 6 เดือนมาเลย ใช้ได้จริง','Got a real 6-month data study plan','s4',9),
  R(5,['kind','recommend'],'ซ้อมสัมภาษณ์ให้ 2 รอบ มั่นใจขึ้นเยอะ','Two rounds of mock interviews, I feel way more confident','b3',9),
  R(5,['real'],'บอกตรง ๆ ว่าพอร์ตยังขาดอะไร','Told me honestly what my portfolio was missing','s4',8),
  R(5,['ontime','direct'],'ตรงเวลา กระชับ ได้เนื้อหาเต็ม 30 นาที','On time and focused, a full 30 minutes of content','c4',7)],
 m4:[R(5,['resume','direct'],'พี่อ่านเรซูเม่ 10 วินาทีแล้วชี้จุดผิดได้ทันที','Spotted my resume problems in about ten seconds','b3',9),
  R(4,['real'],'รู้สิทธิแรงงานมากขึ้น แต่อยากให้มีเอกสารสรุปให้','Learned a lot about labor rights, would love a summary sheet','g0',9,['ขอบคุณที่บอกนะ ต่อไปจะส่งสรุปให้ทุกคนหลังคุย','Thanks for the tip, I’ll send a summary after every session now']),
  R(5,['kind','resume'],'ใจดี ไม่ดุ แก้เรซูเม่ให้ละเอียดมาก','Kind, not scary at all, very detailed resume feedback','f4',8),
  R(4,['ontime'],'ได้ข้อมูลดี แต่ราคาสูงไปนิดสำหรับนักศึกษา','Good info, a bit pricey for students','m2',8),
  R(5,['recommend','real'],'HR ตัวจริง บอกเลยว่าบริษัทมองอะไร','A real HR pro who tells you what companies look for','g1',7),
  R(5,['direct'],'ตอบคำถามยาก ๆ เรื่องลาออกได้ชัดเจน','Gave clear answers on tricky resignation questions','g1',6)],
 m5:[R(5,['kind','real'],'คุยสนุกมาก ได้รู้จักงานหมักจริง ๆ','So fun to talk to, I learned what fermentation work is really like','f3',9),
  R(5,['recommend'],'ช่วยหาที่ฝึกงานสายเครื่องดื่มให้ด้วย','Even helped me find a drinks internship','f4',8),
  R(4,['direct'],'ดีมาก แต่สัญญาณเน็ตพี่หลุดนิดหน่อย','Great, though her connection dropped a little','m2',7,['ขอโทษด้วยน้า ย้ายมาคุยในห้องที่เน็ตดีแล้ว','Sorry about that! I moved to a room with better wifi'])],
 m6:[R(5,['real','direct'],'เล่าเรื่อง OT ในแล็บตรง ๆ ช่วยตัดสินใจได้เยอะ','Honest about overtime in labs, really helped me decide','c4',9),
  R(4,['ontime'],'ตรงเวลา ได้ข้อมูล ISO 17025 ครบ','On time, covered ISO 17025 well','m4',9),
  R(4,['kind'],'ใจดี แต่อยากได้ตัวอย่างข้อสอบเข้างานมากกว่านี้','Kind, but I wanted more sample test questions','m2',8),
  R(5,['recommend','real'],'ถ้าจะทำแล็บ ควรคุยก่อนสมัคร','Talk to him before applying to any lab','c4',8),
  R(5,['direct'],'แนะนำวิธีรับมือหัวหน้าได้ใช้จริง','Gave practical tips for handling a tough boss','g1',7),
  R(4,['real','ontime'],'ข้อมูลดี แต่ช่วงท้ายรีบไปหน่อย','Good info, the ending felt a bit rushed','m4',6),
  R(5,['kind'],'พูดเพราะ ฟังเข้าใจง่าย','Friendly and easy to understand','m2',6)],
 m7:[R(5,['resume','kind'],'พอร์ตดูโปรขึ้นมาก ได้งานดีไซน์แรกแล้ว!','My portfolio looks so much better, I got my first design job!','d3',9,['ยินดีด้วยมาก ๆ!','Huge congrats!']),
  R(5,['direct'],'ชี้จุดที่ต้องแก้ในพอร์ตแบบชัดเจน','Pointed out exactly what to fix in my portfolio','d3',8),
  R(5,['recommend','real'],'ย้ายสายจากชีวะได้เหมือนพี่ ขอบคุณมาก','I switched from biology just like her, thank you!','m4',7)],
 m8:[R(5,['direct','real'],'บอกช่วงเงินเดือนที่ควรขอได้เป๊ะมาก','Told me exactly what salary range to ask for','g0',9),
  R(5,['recommend'],'ได้ข้อเสนอจากที่ที่อยากไปแล้ว','I got an offer from my top choice','g0',9),
  R(4,['resume','ontime'],'แก้เรซูเม่ดี แต่อยากได้ตัวอย่างอีเมลสมัครงาน','Good resume fixes, I also wanted a sample cover email','b3',8,['ส่งตัวอย่างให้ทางแชตแล้วนะ','I sent you a sample in chat']),
  R(5,['kind','direct'],'เป็นกันเอง ถามอะไรก็ตอบ','Friendly, answered everything','s4',8),
  R(5,['real'],'รู้ว่า recruiter มองอะไรจากใบสมัคร','Now I know what recruiters look for','g1',7),
  R(4,['direct'],'ดีมาก แต่ 30 นาทีสั้นไปหน่อย','Great, 30 minutes just felt short','b3',6),
  R(5,['recommend','kind'],'แนะนำให้ทุกคนที่หางานแรก','Recommended for anyone hunting for a first job','g0',6),
  R(5,['resume'],'เรซูเม่ผ่านรอบแรกเพิ่มขึ้นเยอะ','My resume gets past the first round much more now','f4',5)],
 m9:[R(5,['kind'],'พี่ใจดีมาก เล่าชีวิตงานประกันคุณภาพให้ฟังละเอียด','Very kind, explained QA work in detail','f3',9)]
};
const SLOTS=[['ส. 27 ก.ย. 10:00','Sat 27 Sep 10:00'],['ส. 27 ก.ย. 14:00','Sat 27 Sep 14:00'],['อา. 28 ก.ย. 19:00','Sun 28 Sep 19:00'],['อ. 30 ก.ย. 20:00','Tue 30 Sep 20:00']];
const NOTIFS=[
 {ic:'📝',t:['มีรีวิวใหม่ของ คลาวด์บัน เทค','New review for Cloudbun Tech'],w:['5 นาทีที่แล้ว','5 min ago'],go:['company','cloudbun'],read:false},
 {ic:'💼',t:['ไบโอเฟรช เปิดรับฝึกงาน QC แล้ว','BioFresh opened a QC internship'],w:['1 ชม.','1 hr ago'],go:['jobs'],read:false},
 {ic:'💬',t:['พี่มิ้นท์ตอบกระทู้ “ฝึกงาน QC โรงงานอาหาร”','Mint answered “QC internship at a food factory”'],w:['เมื่อวาน','Yesterday'],go:['ask'],read:true},
];
const CATS=[['pay',['เงินเดือน','Pay']],['benefit',['สวัสดิการ','Benefits']],['boss',['หัวหน้า','Management']],['wlb',['Work-life balance','Work-life balance']],['growth',['ความก้าวหน้า','Career growth']],['culture',['สังคมในที่ทำงาน','Culture']]];
const TYPE={emp:['พนักงาน','Employee'],intern:['ฝึกงาน','Intern']};
const DIFF={easy:['ง่าย','Easy','good'],mid:['ปานกลาง','Medium','mid'],hard:['ยาก','Hard','bad']};
const IND={food:['อาหารและเครื่องดื่ม','Food & beverage'],lab:['แล็บตรวจวิเคราะห์','Testing lab'],pharma:['ยาและเวชภัณฑ์','Pharmaceuticals'],tech:['เทคโนโลยี / สตาร์ทอัพ','Tech / startup'],retail:['ค้าปลีก','Retail'],ferment:['เครื่องดื่มหมัก','Fermented drinks'],bank:['การเงินและธนาคาร','Banking & finance'],health:['โรงพยาบาลและสุขภาพ','Hospitals & health'],logistics:['โลจิสติกส์','Logistics'],hotel:['โรงแรมและท่องเที่ยว','Hotels & tourism'],auto:['ยานยนต์และการผลิต','Automotive & manufacturing'],agency:['เอเจนซี่และครีเอทีฟ','Agency & creative'],game:['เกมและสื่อดิจิทัล','Games & digital media'],energy:['พลังงาน','Energy'],beauty:['เครื่องสำอางและความงาม','Beauty & cosmetics'],airline:['สายการบินและการบิน','Airlines & aviation']};
const CO=[
 {id:'biofresh',name:['ไบโอเฟรช ฟู้ดส์','BioFresh Foods'],mk:['บฟ','BF'],hue:'#FFE08A',ind:'food',size:1200,loc:['บางนา-ตราด กม.19','Bangna-Trad km 19'],transit:['รถรับส่งจาก BTS อุดมสุข','Shuttle from BTS Udom Suk'],overall:4.1,
  cats:{pay:3.8,benefit:4.3,boss:3.9,wlb:3.6,growth:4.0,culture:4.4},mood:[62,28,10],trend:38,
  ai:{pros:[['สวัสดิการครบ มีรถรับส่งและข้าวกลางวันฟรี','Solid benefits, with a free shuttle and free lunch'],['พี่เลี้ยงฝึกงานสอนงานแล็บจริง ได้จับ QC ตั้งแต่สัปดาห์แรก','Intern mentors teach real lab work; hands-on QC from week one'],['รับเด็กฝึกงานเป็นพนักงานบ่อย','Interns are often hired full-time']],
      cons:[['ช่วงออดิตโรงงาน OT หนัก','Heavy overtime during factory audits'],['ทำงานเป็นกะในไลน์ผลิต','Shift work on the production line'],['เงินเดือนเริ่มต้นกลาง ๆ เมื่อเทียบกับกลุ่มยา','Starting pay is average compared with pharma']]},
  reality:[[['OT จ่ายตามกฎหมาย','OT paid by law'],['จ่ายจริง ครบ 1.5 เท่า','Paid in full at 1.5x'],'ok'],[['เข้างาน 8:00–17:00','Hours 8:00–17:00'],['ช่วงออดิตมักอยู่ถึง 19:00','Often until 19:00 during audits'],'meh'],[['โบนัสตามผลประกอบการ','Performance bonus'],['ปีล่าสุดได้ 2 เดือน','2 months last year'],'ok'],[['ทำงานที่บ้านได้','Work from home'],['ทำได้เฉพาะฝ่ายออฟฟิศ','Office roles only'],'no']],
  salary:[[['QC Analyst (จบใหม่)','QC Analyst (new grad)'],18000,21000,25000,42],[['QA Officer','QA Officer'],24000,28500,35000,27],[['R&D Food Scientist','R&D Food Scientist'],28000,34000,45000,15],[['นักศึกษาฝึกงาน (เบี้ยเลี้ยง)','Intern (allowance)'],300,350,400,31,'day']],
  interview:{rounds:2,days:['7–10 วัน','7–10 days'],diff:'mid',qs:[['อธิบายขั้นตอนตรวจ Coliform ในตัวอย่างอาหาร','Walk through a coliform test on a food sample'],['ถ้าพบค่าจุลินทรีย์เกินสเปกในล็อตที่กำลังจะส่ง จะทำอย่างไร','A lot about to ship is over the microbial spec. What do you do?'],['รู้จัก GMP / HACCP แค่ไหน','How well do you know GMP / HACCP?'],['สอบข้อเขียนเรื่องการเตรียมอาหารเลี้ยงเชื้อ','Written test on preparing culture media']]},
  reviews:[
   {role:['นักศึกษาฝึกงาน QC','QC Intern'],type:'intern',mood:0,r:5,t:['ฝึกงานที่ได้ทำงานจริง ไม่ได้แค่ถ่ายเอกสาร','An internship with real work, not just photocopying'],p:['พี่เลี้ยงใจดี สอนเพาะเชื้อ นับโคโลนีทุกวัน ได้เบี้ยเลี้ยงและข้าวฟรี','Kind mentor, daily plating and colony counts, allowance and free lunch'],c:['ต้องตื่นเช้าไปขึ้นรถรับส่ง 6:30','The shuttle leaves at 6:30'],d:'Q2 2026',v:true,h:48},
   {role:['QA Officer','QA Officer'],type:'emp',mood:0,r:4,t:['สวัสดิการดี ทีมน่ารัก แต่ช่วงออดิตเหนื่อย','Good benefits, lovely team, tiring audit season'],p:['ประกันกลุ่มดี มีกองทุนสำรองเลี้ยงชีพ 5%','Good group insurance and a 5% provident fund'],c:['เอกสารเยอะมากช่วงลูกค้าต่างประเทศมาออดิต','Mountains of paperwork when overseas clients audit'],d:'Q3 2026',v:true,h:31},
   {role:['Production Supervisor','Production Supervisor'],type:'emp',mood:1,r:3,t:['มั่นคง แต่ทำงานเป็นกะ','Stable, but shift-based'],p:['บริษัทใหญ่ ไม่ต้องกลัวเลิกจ้าง','Big company, little layoff risk'],c:['กะดึกสลับทุก 2 สัปดาห์ ร่างกายปรับตัวยาก','Night shift every other fortnight is hard on the body'],d:'Q1 2026',v:false,h:12},
   {role:['R&D','R&D'],type:'emp',mood:0,r:5,t:['ได้คิดสูตรใหม่จริง ของออกขายในเซเว่น','I create real recipes that end up on store shelves'],p:['ได้เห็นผลงานตัวเองบนชั้นวางสินค้า','Seeing your own product on the shelf'],c:['งบวิจัยต้องผ่านหลายขั้น','Research budgets need many approvals'],d:'Q2 2026',v:true,h:22},
   {role:['QC Analyst','QC Analyst'],type:'emp',mood:2,r:2,t:['หัวหน้าบางแผนกพูดจาแรง','Some department heads are harsh'],p:['เพื่อนร่วมงานดี','Good coworkers'],c:['ถูกตำหนิต่อหน้าคนอื่นบ่อย','Often criticized in front of others'],d:'Q4 2025',v:true,h:9,reply:['ขอบคุณสำหรับความเห็นค่ะ เราจัดอบรมการให้ฟีดแบ็กสำหรับหัวหน้าทุกแผนกแล้วในไตรมาสนี้ — ทีม HR','Thank you for the feedback. We ran feedback training for every department head this quarter. — HR team']}]},
 {id:'siamlab',name:['สยามแล็บ อนาลิติกส์','Siam Lab Analytics'],mk:['สล','SL'],hue:'#BDEBDD',ind:'lab',size:280,loc:['ลาดพร้าว','Lat Phrao'],transit:['MRT ลาดพร้าว เดิน 8 นาที','8-min walk from MRT Lat Phrao'],overall:3.6,
  cats:{pay:3.2,benefit:3.4,boss:3.8,wlb:3.1,growth:4.1,culture:3.9},mood:[41,39,20],trend:14,
  ai:{pros:[['ได้จับเครื่องมือหลายแบบ ทั้ง PCR และ HPLC','Hands-on with many instruments, from PCR to HPLC'],['เหมาะกับคนจบใหม่ที่อยากเก็บประสบการณ์ ISO 17025','Great for new grads wanting ISO 17025 experience'],['เดินทางสะดวก ใกล้ MRT','Easy commute near the MRT']],
      cons:[['ตัวอย่างเข้าเยอะ ต้องเร่งส่งผลทันเวลา','High sample volume and tight turnaround'],['เงินเดือนต่ำกว่าตลาดเล็กน้อย','Pay slightly below market'],['เสาร์เว้นเสาร์','Every other Saturday']]},
  reality:[[['ทำงานจันทร์–ศุกร์','Mon–Fri'],['เสาร์เว้นเสาร์','Plus every other Saturday'],'no'],[['OT จ่ายตามกฎหมาย','OT paid by law'],['จ่ายจริง','Paid'],'ok'],[['อบรมต่อเนื่อง','Ongoing training'],['ส่งอบรมปีละ 2–3 ครั้ง','2–3 courses a year'],'ok'],[['ขึ้นเงินเดือนทุกปี','Annual raise'],['เฉลี่ย 3%','About 3%'],'meh']],
  salary:[[['Lab Analyst (จบใหม่)','Lab Analyst (new grad)'],16500,18500,22000,38],[['Microbiologist','Microbiologist'],20000,24000,30000,19],[['Quality Manager','Quality Manager'],45000,55000,70000,4]],
  interview:{rounds:2,days:['5 วัน','5 days'],diff:'easy',qs:[['เคยใช้ Autoclave และ Laminar flow ไหม','Have you used an autoclave and laminar flow hood?'],['ทำ Gram stain ให้ดูสด ๆ','Do a Gram stain on the spot'],['ทำงานวันเสาร์ได้ไหม','Can you work Saturdays?']]},
  reviews:[
   {role:['Lab Analyst','Lab Analyst'],type:'emp',mood:1,r:3,t:['ได้ความรู้เยอะ แต่งานล้นมือ','Learned a lot, but swamped'],p:['ได้ทำทั้งจุลชีวะและเคมี เรซูเม่ดูดีขึ้นเยอะ','Both micro and chemistry work; great for the resume'],c:['ตัวอย่างเข้าเยอะช่วงปลายเดือน','Sample flood at month end'],d:'Q3 2026',v:true,h:26},
   {role:['นักศึกษาฝึกงาน','Intern'],type:'intern',mood:0,r:4,t:['เหมาะกับคนอยากฝึกมือ','Good for building lab skills'],p:['พี่ ๆ ปล่อยให้ลองทำเอง','Seniors let you try things yourself'],c:['ไม่มีเบี้ยเลี้ยง','No allowance'],d:'Q2 2026',v:false,h:17},
   {role:['Microbiologist','Microbiologist'],type:'emp',mood:2,r:2,t:['ทำเสาร์เว้นเสาร์ เหนื่อยสะสม','Alternate Saturdays wear you down'],p:['หัวหน้าเข้าใจ ยืดหยุ่นเรื่องลา','Understanding boss, flexible leave'],c:['ค่าแรงไม่ขยับตามภาระงาน','Pay does not match the workload'],d:'Q1 2026',v:true,h:14},
   {role:['Admin','Admin'],type:'emp',mood:1,r:4,t:['บรรยากาศเป็นกันเอง','Friendly atmosphere'],p:['เพื่อนร่วมงานดี','Good coworkers'],c:['ระบบเอกสารยังเป็นกระดาษ','Still paper-based'],d:'Q4 2025',v:false,h:3}]},
 {id:'northstar',name:['นอร์ธสตาร์ ฟาร์มา','Northstar Pharma'],mk:['นส','NS'],hue:'#C9DBFF',ind:'pharma',size:650,loc:['นิคมบางปู สมุทรปราการ','Bang Poo Industrial Estate'],transit:['รถรับส่งจาก BTS เคหะฯ','Shuttle from BTS Kheha'],overall:3.9,
  cats:{pay:4.3,benefit:4.1,boss:3.5,wlb:3.7,growth:3.6,culture:3.8},mood:[52,33,15],trend:9,
  ai:{pros:[['เงินเดือนสูงกว่ากลุ่มอาหาร','Pays more than the food sector'],['ระบบ GMP เข้มข้น ได้มาตรฐานสากล','Rigorous GMP to international standards'],['โบนัสสม่ำเสมอ','Consistent bonuses']],
      cons:[['กฎระเบียบเยอะ เปลี่ยนแปลงช้า','Lots of rules, slow to change'],['เลื่อนตำแหน่งต้องรอนาน','Long wait for promotion'],['ใส่ชุดคลีนรูมทั้งวัน','Cleanroom gowning all day']]},
  reality:[[['โบนัส 2–4 เดือน','2–4 month bonus'],['ส่วนใหญ่ได้ 3 เดือน','Usually 3 months'],'ok'],[['เติบโตในสายงาน','Career growth'],['ต้องรอตำแหน่งว่าง','Wait for an opening'],'meh'],[['ทำงานที่บ้านได้','Work from home'],['ทำไม่ได้','Not possible'],'no'],[['ประกันสุขภาพครอบครัว','Family health insurance'],['ครอบคลุมคู่สมรสและบุตร','Covers spouse and children'],'ok']],
  salary:[[['QC Microbiologist','QC Microbiologist'],25000,29000,36000,21],[['Validation Officer','Validation Officer'],30000,36000,48000,11],[['Production Pharmacist','Production Pharmacist'],35000,42000,55000,9]],
  interview:{rounds:3,days:['2–3 สัปดาห์','2–3 weeks'],diff:'hard',qs:[['Environmental monitoring ในคลีนรูมทำอย่างไร','How is cleanroom environmental monitoring done?'],['อธิบาย Sterility test','Explain a sterility test'],['สอบภาษาอังกฤษ TOEIC ภายใน','In-house TOEIC-style English test'],['สัมภาษณ์กับผู้จัดการชาวต่างชาติ','Interview with an expat manager']]},
  reviews:[
   {role:['QC Microbiologist','QC Microbiologist'],type:'emp',mood:0,r:4,t:['เงินดี งานเป๊ะ','Good pay, precise work'],p:['ได้ฐานเงินเดือนดีตั้งแต่เริ่ม','Strong base pay from day one'],c:['ทุกอย่างต้องมีเอกสาร SOP','Everything needs an SOP'],d:'Q3 2026',v:true,h:19},
   {role:['Validation','Validation'],type:'emp',mood:1,r:3,t:['มั่นคงแต่โตช้า','Stable but slow growth'],p:['สวัสดิการครอบครัวดีมาก','Excellent family benefits'],c:['รอเลื่อนขั้น 4 ปียังไม่ได้','4 years and still no promotion'],d:'Q2 2026',v:true,h:11},
   {role:['นักศึกษาฝึกงาน','Intern'],type:'intern',mood:0,r:4,t:['ได้เห็นระบบยาของจริง','See a real pharma system'],p:['มีเบี้ยเลี้ยงวันละ 400','400 baht daily allowance'],c:['ส่วนใหญ่ได้แค่ดู ไม่ค่อยได้ลงมือ','Mostly observing, little hands-on'],d:'Q2 2026',v:false,h:8}]},
 {id:'cloudbun',name:['คลาวด์บัน เทค','Cloudbun Tech'],mk:['คบ','CB'],hue:'#FFD0BE',ind:'tech',size:120,loc:['อารีย์','Ari'],transit:['BTS อารีย์ เดิน 3 นาที','3-min walk from BTS Ari'],overall:4.4,
  cats:{pay:4.2,benefit:4.0,boss:4.6,wlb:4.5,growth:4.4,culture:4.7},mood:[78,17,5],trend:22,
  ai:{pros:[['ทำงานไฮบริด เข้าออฟฟิศ 2 วันต่อสัปดาห์','Hybrid: 2 office days a week'],['หัวหน้าฟังความเห็นจริง','Managers really listen'],['มีงบเรียนคอร์สออนไลน์ปีละ 20,000 บาท','20,000 baht yearly learning budget']],
      cons:[['สตาร์ทอัพ เป้าเปลี่ยนเร็ว','Startup goals change fast'],['โบนัสไม่แน่นอน','Bonus is uncertain'],['บางทีมงานเยอะช่วงออกฟีเจอร์ใหม่','Crunch before feature launches']]},
  reality:[[['ไฮบริด','Hybrid'],['เข้าออฟฟิศ 2 วันจริง','Really 2 office days'],'ok'],[['วันลาไม่จำกัด','Unlimited leave'],['ใช้ได้จริงเฉลี่ย 18 วัน','About 18 days used on average'],'ok'],[['โบนัส','Bonus'],['ปีนี้งด','Skipped this year'],'no'],[['ขึ้นเงินเดือนทุกปี','Annual raise'],['8–12%','8–12%'],'ok']],
  salary:[[['Data Analyst','Data Analyst'],32000,38000,48000,14],[['Product Designer','Product Designer'],35000,42000,55000,9],[['Software Engineer','Software Engineer'],40000,55000,80000,23],[['Customer Success','Customer Success'],22000,26000,32000,9],[['Product Manager','Product Manager'],40000,48000,60000,5]],
  interview:{rounds:3,days:['10 วัน','10 days'],diff:'mid',qs:[['ทำ Take-home assignment 3 วัน','3-day take-home assignment'],['เล่าโปรเจกต์ที่ภูมิใจที่สุด','Tell us about your proudest project'],['Culture fit กับ CEO','Culture-fit chat with the CEO']]},
  reviews:[
   {role:['Data Analyst','Data Analyst'],type:'emp',mood:0,r:5,t:['ที่ทำงานที่ไม่อยากตื่นมาเกลียดวันจันทร์','A job that does not make you dread Mondays'],p:['ทีมเก่ง หัวหน้าใจดี ไฮบริดจริง','Smart team, kind boss, real hybrid'],c:['โบนัสปีนี้ไม่มี','No bonus this year'],d:'Q3 2026',v:true,h:57},
   {role:['Software Engineer','Software Engineer'],type:'emp',mood:0,r:4,t:['เรียนรู้เร็วมาก','You learn very fast'],p:['ได้ถือโปรเจกต์ใหญ่ตั้งแต่ปีแรก','Own big projects in year one'],c:['ช่วงก่อนปล่อยฟีเจอร์ต้องทำดึก','Late nights before launches'],d:'Q2 2026',v:true,h:21},
   {role:['Marketing','Marketing'],type:'emp',mood:1,r:4,t:['สนุก แต่ต้องรับมือกับการเปลี่ยนแปลงได้','Fun if you handle change well'],p:['ได้ลองอะไรใหม่ ๆ','Lots of new things to try'],c:['เป้าหมายเปลี่ยนทุกไตรมาส','Goals change every quarter'],d:'Q1 2026',v:false,h:6}]},
 {id:'megamart',name:['เมกะมาร์ท รีเทล','Megamart Retail'],mk:['มม','MM'],hue:'#FFD3E2',ind:'retail',size:8000,loc:['สำนักงานใหญ่ พระราม 9','HQ, Rama 9'],transit:['MRT พระราม 9 เดิน 5 นาที','5-min walk from MRT Rama 9'],overall:3.1,
  cats:{pay:3.0,benefit:3.5,boss:2.8,wlb:2.6,growth:3.4,culture:3.2},mood:[28,37,35],trend:51,
  ai:{pros:[['องค์กรใหญ่ มั่นคง','Large and stable'],['ส่วนลดพนักงาน 10%','10% staff discount'],['ย้ายแผนกภายในได้','Internal transfers possible']],
      cons:[['ประชุมเยอะ ตัดสินใจช้า','Many meetings, slow decisions'],['หัวหน้าบางคนสั่งงานนอกเวลา','Some bosses message after hours'],['เป้ายอดขายกดดัน','High sales pressure']]},
  reality:[[['ทำงาน 5 วัน','5-day week'],['สาขาทำ 6 วัน','Stores work 6 days'],'no'],[['OT จ่ายตามกฎหมาย','OT paid by law'],['สำนักงานใหญ่ไม่มี OT','No OT pay at HQ'],'no'],[['โบนัส 1–3 เดือน','1–3 month bonus'],['ส่วนใหญ่ 1.5 เดือน','Usually 1.5 months'],'meh']],
  salary:[[['Category Analyst','Category Analyst'],25000,30000,38000,33],[['Store Manager','Store Manager'],35000,42000,55000,18],[['QA อาหารสด','Fresh Food QA'],22000,26000,32000,12],[['เจ้าหน้าที่การตลาด','Marketing Executive'],21000,25000,32000,14],[['เจ้าหน้าที่ HR','HR Officer'],19000,23500,30000,9],[['นักบัญชี','Accountant'],18000,22000,28000,12]],
  interview:{rounds:2,days:['2 สัปดาห์','2 weeks'],diff:'easy',qs:[['ถ้ายอดขายตกจะทำอย่างไร','What would you do if sales dropped?'],['เข้างานวันหยุดได้ไหม','Can you work on holidays?']]},
  reviews:[
   {role:['QA อาหารสด','Fresh Food QA'],type:'emp',mood:2,r:2,t:['LINE หัวหน้าเด้งตอนสี่ทุ่ม','Boss messages at 10 p.m.'],p:['ได้เรียนรู้ระบบห่วงโซ่ความเย็น','Learned cold-chain systems'],c:['ไม่มีเส้นแบ่งเวลางานกับเวลาส่วนตัว','No line between work and personal time'],d:'Q3 2026',v:true,h:73,reply:['เราออกนโยบาย “ไม่ส่งงานหลัง 19:00” แล้ว หากยังพบ แจ้ง HR ได้โดยไม่ระบุตัวตน — ฝ่ายบุคคล','We introduced a “no messages after 19:00” policy. If it still happens, report it to HR anonymously. — People team']},
   {role:['Category Analyst','Category Analyst'],type:'emp',mood:1,r:3,t:['มั่นคงดี แต่ช้า','Stable but slow'],p:['ส่วนลดพนักงาน สวัสดิการพื้นฐานครบ','Staff discount, all basic benefits'],c:['ประชุมวันละ 4 รอบ','Four meetings a day'],d:'Q2 2026',v:true,h:29},
   {role:['นักศึกษาฝึกงาน','Intern'],type:'intern',mood:1,r:3,t:['ได้เห็นภาพธุรกิจใหญ่','See how a big business runs'],p:['มีเบี้ยเลี้ยง','Allowance provided'],c:['งานส่วนใหญ่เป็นงานเอกสาร','Mostly paperwork'],d:'Q1 2026',v:false,h:5}]},
 {id:'greencap',name:['กรีนแคป บริวอรี่','Greencap Brewery'],mk:['กค','GC'],hue:'#DDF0B5',ind:'ferment',size:90,loc:['นครปฐม','Nakhon Pathom'],transit:['ควรมีรถส่วนตัว','A car helps'],overall:4.0,
  cats:{pay:3.6,benefit:3.7,boss:4.3,wlb:4.2,growth:3.8,culture:4.5},mood:[60,30,10],trend:6,
  ai:{pros:[['ได้ทำงานหมักจริงตั้งแต่ยีสต์ถึงขวด','Real fermentation work from yeast to bottle'],['ทีมเล็ก เจ้าของเข้าถึงง่าย','Small team, approachable owner'],['บรรยากาศสบาย','Relaxed atmosphere']],
      cons:[['อยู่ไกลเมือง','Far from the city'],['เงินเดือนเริ่มต้นไม่สูง','Modest starting pay'],['ต้องยกของหนักบ้าง','Some heavy lifting']]},
  reality:[[['ทำงาน 5 วัน','5-day week'],['ทำ 5 วันจริง','Really 5 days'],'ok'],[['ที่พักให้','Housing provided'],['มีหอพักพนักงานฟรี','Free staff dorm'],'ok'],[['โบนัส','Bonus'],['ขึ้นกับยอดขาย','Depends on sales'],'meh']],
  salary:[[['Fermentation Technician','Fermentation Technician'],18000,21000,26000,8],[['QC Microbiologist','QC Microbiologist'],20000,23500,28000,6]],
  interview:{rounds:1,days:['3 วัน','3 days'],diff:'easy',qs:[['เคยเลี้ยงยีสต์ไหม','Have you cultured yeast?'],['ทำไมสนใจงานหมัก','Why fermentation?'],['ทดลองชิมและบรรยายรสชาติ','Taste and describe a sample']]},
  reviews:[
   {role:['Fermentation Technician','Fermentation Technician'],type:'emp',mood:0,r:5,t:['สวรรค์ของคนจบจุลชีวะที่ชอบงานหมัก','Heaven for microbiology grads who love fermentation'],p:['ได้ทำจริงทุกขั้น เจ้าของสอนเอง','Hands-on at every step, taught by the owner'],c:['ไกลมาก ต้องย้ายไปอยู่หอ','Very far; you move into the dorm'],d:'Q3 2026',v:true,h:34},
   {role:['นักศึกษาฝึกงาน','Intern'],type:'intern',mood:0,r:4,t:['ฝึกงานสนุกที่สุดที่เคยได้ยิน','The most fun internship I have heard of'],p:['มีหอพักฟรี ได้ลองสูตรใหม่','Free dorm, got to test new recipes'],c:['ห่างไกลร้านสะดวกซื้อ','Far from convenience stores'],d:'Q2 2026',v:false,h:15}]},
 {id:'srisiam',name:['ศรีสยาม แบงก์','Srisiam Bank'],mk:['ศส','SB'],hue:'#CDE6FF',ind:'bank',size:15000,loc:['สำนักงานใหญ่ สีลม','HQ, Silom'],transit:['BTS ศาลาแดง เดิน 4 นาที','4-min walk from BTS Sala Daeng'],overall:3.8,
  cats:{pay:4.2,benefit:4.5,boss:3.4,wlb:3.3,growth:3.7,culture:3.5},mood:[45,38,17],trend:44,
  ai:{pros:[['สวัสดิการแน่น ดอกเบี้ยบ้านพนักงานต่ำ','Strong benefits, including low staff mortgage rates'],['โบนัสสม่ำเสมอ 3–5 เดือน','Reliable 3–5 month bonus'],['มีโครงการ Management Trainee','Management trainee program']],
      cons:[['ลำดับขั้นเยอะ อนุมัติช้า','Many layers; slow approvals'],['ปิดงบสิ้นเดือนกลับดึก','Late nights at month-end close'],['แต่งตัวทางการทุกวัน','Formal dress every day']]},
  reality:[[['โบนัส 3–6 เดือน','3–6 month bonus'],['ส่วนใหญ่ได้ 4 เดือน','Usually 4 months'],'ok'],[['ทำงานไฮบริด','Hybrid work'],['เฉพาะบางฝ่าย','Only some departments'],'meh'],[['เลิกงาน 17:30','Finish at 17:30'],['ช่วงปิดงบถึง 21:00','Until 21:00 at month-end'],'no']],
  salary:[[['Management Trainee','Management Trainee'],30000,35000,42000,36],[['Credit Analyst','Credit Analyst'],28000,34000,45000,22],[['Relationship Manager','Relationship Manager'],35000,45000,65000,18],[['นิติกร','Legal Officer'],25000,30000,38000,8],[['เจ้าหน้าที่กำกับดูแล','Compliance Officer'],26000,31000,40000,10],[['เจ้าหน้าที่พัฒนาบุคลากร','Learning & Development Officer'],24000,28000,35000,6]],
  interview:{rounds:4,days:['3–4 สัปดาห์','3–4 weeks'],diff:'hard',qs:[['สอบ Aptitude test ออนไลน์','Online aptitude test'],['Case study วิเคราะห์สินเชื่อ','Credit analysis case study'],['Group discussion กับผู้สมัครคนอื่น','Group discussion with other candidates']]},
  reviews:[
   {role:['Management Trainee','Management Trainee'],type:'emp',mood:0,r:4,t:['ได้หมุนงานหลายฝ่าย เปิดโลกมาก','Rotating through teams really opens your eyes'],p:['ได้เจอผู้บริหารระดับสูงบ่อย','Frequent access to senior leaders'],c:['เป้าหมายสูง กดดันตลอดโปรแกรม','High targets and pressure throughout'],d:'Q3 2026',v:true,h:39},
   {role:['เจ้าหน้าที่สาขา','Branch officer'],type:'emp',mood:2,r:2,t:['เป้าขายประกันหนักกว่างานหลัก','Insurance sales targets outweigh the real job'],p:['สวัสดิการดี','Good benefits'],c:['ต้องขายผลิตภัณฑ์ให้ลูกค้าทุกวัน','Daily cross-selling targets'],d:'Q2 2026',v:true,h:52},
   {role:['นักศึกษาฝึกงาน','Intern'],type:'intern',mood:1,r:3,t:['ได้เห็นระบบธนาคารจริง','See how a real bank runs'],p:['มีเบี้ยเลี้ยงวันละ 500','500 THB daily allowance'],c:['งานส่วนใหญ่เป็นกรอกข้อมูล','Mostly data entry'],d:'Q1 2026',v:false,h:11}]},
 {id:'wellness',name:['เวลเนส แคร์ ฮอสพิทัล','Wellness Care Hospital'],mk:['วค','WC'],hue:'#C8F0E6',ind:'health',size:2200,loc:['รัชดาภิเษก','Ratchadaphisek'],transit:['MRT ห้วยขวาง เดิน 6 นาที','6-min walk from MRT Huai Khwang'],overall:3.7,
  cats:{pay:3.6,benefit:4.2,boss:3.6,wlb:3.0,growth:3.9,culture:4.0},mood:[48,35,17],trend:27,
  ai:{pros:[['ตรวจสุขภาพและรักษาฟรีสำหรับพนักงาน','Free healthcare for staff'],['งานมีความหมาย ได้ช่วยคนจริง','Meaningful work helping people'],['แล็บจุลชีวะคลินิกมีเครื่องมือทันสมัย','Modern clinical microbiology lab']],
      cons:[['เวรดึกและวันหยุดนักขัตฤกษ์','Night and holiday shifts'],['งานเร่งช่วงผู้ป่วยเยอะ','Rush periods with patient surges'],['เงินเดือนเริ่มต้นกลาง ๆ','Average starting pay']]},
  reality:[[['ทำงานเป็นกะ มีค่ากะ','Shift allowance paid'],['จ่ายจริงทุกกะ','Paid for every shift'],'ok'],[['วันหยุดตามปฏิทิน','Public holidays off'],['ต้องสลับเวรวันหยุด','Holiday shifts rotate'],'no'],[['ทุนเรียนต่อ','Study scholarships'],['มีจริง ต้องใช้ทุนคืน','Yes, with a work bond'],'meh']],
  salary:[[['นักเทคนิคการแพทย์','Medical Technologist'],22000,26000,32000,31],[['Clinical Microbiologist','Clinical Microbiologist'],24000,28000,35000,12],[['พยาบาลวิชาชีพ','Registered Nurse'],25000,30000,40000,48]],
  interview:{rounds:2,days:['1–2 สัปดาห์','1–2 weeks'],diff:'mid',qs:[['ถ้าผลเพาะเชื้อปนเปื้อนจะทำอย่างไร','What do you do if a culture is contaminated?'],['เข้าเวรดึกได้ไหม','Can you work night shifts?'],['เล่าประสบการณ์ฝึกงานในโรงพยาบาล','Describe your hospital internship']]},
  reviews:[
   {role:['นักเทคนิคการแพทย์','Medical Technologist'],type:'emp',mood:0,r:4,t:['งานหนักแต่ภูมิใจ','Hard work but rewarding'],p:['ทีมแล็บสามัคคี หัวหน้าสอนดี','Close-knit lab team, good teaching'],c:['เวรดึกเดือนละ 6–8 ครั้ง','6–8 night shifts a month'],d:'Q3 2026',v:true,h:28},
   {role:['นักศึกษาฝึกงานจุลชีวะคลินิก','Clinical Micro Intern'],type:'intern',mood:0,r:5,t:['ได้เห็นเชื้อจริงจากผู้ป่วย','Real patient isolates every day'],p:['ได้ทำ AST และระบุเชื้อเอง','Did AST and ID work myself'],c:['ต้องระวังเรื่องความปลอดภัยมาก','Strict biosafety rules'],d:'Q2 2026',v:false,h:21},
   {role:['เจ้าหน้าที่ธุรการ','Admin officer'],type:'emp',mood:2,r:2,t:['งานล้น คนไม่พอ','Understaffed and overloaded'],p:['สวัสดิการรักษาพยาบาลดี','Great medical benefits'],c:['ลาพักร้อนยาก','Hard to take leave'],d:'Q1 2026',v:true,h:15}]},
 {id:'speedflow',name:['สปีดโฟลว์ โลจิสติกส์','Speedflow Logistics'],mk:['สฟ','SF'],hue:'#FFE1C2',ind:'logistics',size:3400,loc:['ลาดกระบัง','Lat Krabang'],transit:['Airport Link ลาดกระบัง + รถรับส่ง','Airport Link Lat Krabang + shuttle'],overall:3.4,
  cats:{pay:3.5,benefit:3.3,boss:3.3,wlb:3.0,growth:3.6,culture:3.5},mood:[35,40,25],trend:19,
  ai:{pros:[['เติบโตเร็วตามอีคอมเมิร์ซ','Growing fast with e-commerce'],['ได้ใช้ระบบคลังสินค้าอัตโนมัติ','Work with automated warehouses'],['เลื่อนตำแหน่งเร็วถ้าทำผลงานดี','Fast promotion for strong performers']],
      cons:[['ช่วงเซลใหญ่ 11.11 งานหนักมาก','Brutal during 11.11 sales'],['อยู่ไกลเมือง','Far from the city'],['เปลี่ยนนโยบายบ่อย','Policies change often']]},
  reality:[[['OT จ่ายตามกฎหมาย','OT paid by law'],['จ่ายครบ','Paid in full'],'ok'],[['ทำงาน 5 วัน','5-day week'],['ช่วงเซลทำ 6 วัน','6 days during sales'],'meh'],[['รถรับส่ง','Shuttle bus'],['มีรอบเดียว พลาดแล้วลำบาก','One run only'],'meh']],
  salary:[[['Supply Chain Analyst','Supply Chain Analyst'],25000,30000,38000,20],[['Warehouse Supervisor','Warehouse Supervisor'],22000,27000,33000,26],[['Transport Planner','Transport Planner'],23000,28000,34000,14]],
  interview:{rounds:2,days:['1 สัปดาห์','1 week'],diff:'easy',qs:[['ใช้ Excel ระดับไหน ทำ Pivot ได้ไหม','How good is your Excel? Can you do pivots?'],['ถ้าของส่งไม่ทันจะแก้ยังไง','How would you handle a late shipment?']]},
  reviews:[
   {role:['Supply Chain Analyst','Supply Chain Analyst'],type:'emp',mood:0,r:4,t:['ได้ใช้ข้อมูลจริงเยอะมาก','Lots of real data to work with'],p:['ทีมเด็ก คุยง่าย','Young, easygoing team'],c:['ช่วงเซลต้องอยู่ถึงเที่ยงคืน','Midnight finishes during sales'],d:'Q3 2026',v:true,h:17},
   {role:['Warehouse Supervisor','Warehouse Supervisor'],type:'emp',mood:2,r:2,t:['เหนื่อยกายเหนื่อยใจ','Physically and mentally draining'],p:['OT เยอะ เงินรวมดี','Plenty of paid OT'],c:['ยืนทั้งวัน คนลาออกบ่อย','On your feet all day; high turnover'],d:'Q2 2026',v:true,h:24}]},
 {id:'riverlight',name:['ริเวอร์ไลท์ โฮเทล','Riverlight Hotel'],mk:['รล','RL'],hue:'#F6D9FF',ind:'hotel',size:600,loc:['เจริญกรุง','Charoen Krung'],transit:['BTS สะพานตากสิน เดิน 7 นาที','7-min walk from BTS Saphan Taksin'],overall:3.9,
  cats:{pay:3.1,benefit:3.9,boss:4.0,wlb:3.4,growth:4.1,culture:4.4},mood:[55,32,13],trend:23,
  ai:{pros:[['ได้ฝึกภาษาอังกฤษทุกวัน','Use English every day'],['Service charge เพิ่มรายได้','Service charge boosts income'],['อาหารพนักงานอร่อย','Great staff canteen']],
      cons:[['ทำงานวันหยุดและเทศกาล','Work weekends and holidays'],['เงินเดือนฐานต่ำ','Low base salary'],['ยืนนาน','Long hours standing']]},
  reality:[[['Service charge','Service charge'],['เฉลี่ย 6,000–9,000 บาท/เดือน','Avg 6,000–9,000 THB/month'],'ok'],[['วันหยุด 6 วัน/เดือน','6 days off a month'],['ได้จริง แต่ไม่ตรงเสาร์อาทิตย์','Yes, but rarely weekends'],'meh'],[['ส่วนลดห้องพักเครือ','Chain room discounts'],['ลด 50% ใช้ได้จริง','50% off, really usable'],'ok']],
  salary:[[['Front Office Agent','Front Office Agent'],15000,17000,20000,24],[['F&B Hygiene Officer','F&B Hygiene Officer'],20000,23000,28000,7],[['Sales Executive','Sales Executive'],22000,27000,35000,11]],
  interview:{rounds:2,days:['5 วัน','5 days'],diff:'easy',qs:[['สัมภาษณ์ภาษาอังกฤษ','Interview in English'],['ถ้าแขกโกรธจะรับมือยังไง','How would you handle an angry guest?']]},
  reviews:[
   {role:['F&B Hygiene Officer','F&B Hygiene Officer'],type:'emp',mood:0,r:4,t:['จบจุลชีวะมาทำโรงแรมก็ได้นะ','Microbiology grads fit in hotels too'],p:['ดูแลความสะอาดครัวทั้งโรงแรม','Own food safety for every kitchen'],c:['เชฟบางคนไม่ค่อยฟัง','Some chefs push back'],d:'Q3 2026',v:true,h:33},
   {role:['Front Office Agent','Front Office Agent'],type:'emp',mood:1,r:3,t:['สนุกแต่เหนื่อย','Fun but tiring'],p:['เพื่อนร่วมงานน่ารัก','Lovely coworkers'],c:['กะดึกบ่อย','Frequent night shifts'],d:'Q2 2026',v:false,h:8}]},
 {id:'coralpuff',name:['คอรัลพัฟ บีช รีสอร์ท','Coralpuff Beach Resort'],mk:['คพ','CP'],hue:'#FFE0CC',ind:'hotel',size:320,loc:['หัวหิน ประจวบคีรีขันธ์','Hua Hin, Prachuap Khiri Khan'],transit:['มีรถรับส่งจากตัวเมืองหัวหิน','Shuttle from Hua Hin town'],overall:4.1,
  cats:{pay:3.4,benefit:4.2,boss:4.1,wlb:3.6,growth:3.9,culture:4.5},mood:[60,30,10],trend:9,
  ai:{pros:[['บรรยากาศริมทะเล ทีมเป็นกันเอง','Beachside vibe, friendly team'],['มีหอพักและอาหารพนักงาน','Staff housing and meals'],['หมุนไปลองหลายแผนกได้','Rotate through departments']],
      cons:[['ช่วงไฮซีซันงานหนักมาก','Very busy in high season'],['ไกลกรุงเทพฯ','Far from Bangkok'],['เงินเดือนฐานไม่สูง','Modest base salary']]},
  reality:[[['หอพักพนักงานฟรี','Free staff housing'],['ห้องละ 2 คน สะอาด มีแอร์','2 per room, clean, air-con'],'ok'],[['Service charge','Service charge'],['เฉลี่ย 4,000–7,000 บาท/เดือน ขึ้นกับซีซัน','Avg 4,000–7,000 THB/month, depends on season'],'meh'],[['หยุด 6 วัน/เดือน','6 days off a month'],['ได้จริง แต่ไฮซีซันต้องสลับวันหยุด','Yes, but days off shift in high season'],'meh']],
  salary:[[['Guest Service Agent','Guest Service Agent'],14500,16500,19000,12],[['Housekeeping Attendant','Housekeeping Attendant'],12000,13500,15500,9],[['Spa Receptionist','Spa Receptionist'],15000,17000,20000,5]],
  interview:{rounds:2,days:['1 สัปดาห์','1 week'],diff:'easy',qs:[['แนะนำตัวเป็นภาษาอังกฤษ','Introduce yourself in English'],['ถ้าห้องแขกยังไม่พร้อมตอนเช็กอิน จะทำยังไง','A guest’s room isn’t ready at check-in. What do you do?']]},
  reviews:[
   {role:['Guest Service Agent','Guest Service Agent'],type:'emp',mood:0,r:4,t:['ทำงานริมทะเล ทีมน่ารักมาก','Working by the beach with a lovely team'],p:['หัวหน้าสอนงานใจเย็น ได้ใช้ภาษาอังกฤษทุกวัน','Patient manager, English every day'],c:['ช่วงปีใหม่แทบไม่ได้หยุด','Barely any days off over New Year'],d:'Q3 2026',v:true,h:21},
   {role:['ฝึกงานแผนกแม่บ้าน','Housekeeping intern'],type:'intern',mood:1,r:3,t:['เหนื่อยแต่ได้เรียนรู้เยอะ','Tiring but I learned a lot'],p:['มีหอพักและข้าวให้ 3 มื้อ','Housing and 3 meals provided'],c:['เบี้ยเลี้ยงน้อย ต้องเดินทั้งวัน','Small allowance, on your feet all day'],d:'Q2 2026',v:true,h:14},
   {role:['Spa Receptionist','Spa Receptionist'],type:'emp',mood:0,r:5,t:['ได้ทำงานสายที่ชอบ','Doing work I actually love'],p:['ได้ส่วนลดสปาและห้องพัก','Spa and room discounts'],c:['ต้องขับรถเข้าเมืองเองตอนวันหยุด','Need your own ride into town on days off'],d:'Q2 2026',v:false,h:6}]},
 {id:'thaimotor',name:['ไทยมอเตอร์เวิร์คส์','Thai Motorworks'],mk:['ทม','TM'],hue:'#D6DCE8',ind:'auto',size:5200,loc:['นิคมอมตะ ชลบุรี','Amata Industrial Estate, Chonburi'],transit:['รถรับส่งหลายสายจากชลบุรี','Several shuttle routes in Chonburi'],overall:3.9,
  cats:{pay:4.1,benefit:4.3,boss:3.6,wlb:3.6,growth:3.7,culture:3.6},mood:[50,36,14],trend:15,
  ai:{pros:[['โบนัสสูงและสม่ำเสมอ','High, consistent bonuses'],['ระบบ Kaizen เรียนรู้ได้เยอะ','Learn a lot from kaizen culture'],['มีหอพักและรถรับส่ง','Dorms and shuttles']],
      cons:[['วัฒนธรรมแบบญี่ปุ่น เป๊ะทุกอย่าง','Strict Japanese-style culture'],['อยู่ต่างจังหวัด','Outside Bangkok'],['เลื่อนตำแหน่งตามอายุงาน','Promotion by seniority']]},
  reality:[[['โบนัส 5+ เดือน','5+ month bonus'],['ปีล่าสุด 6.5 เดือน','6.5 months last year'],'ok'],[['OT ตามความสมัครใจ','Voluntary OT'],['แทบทุกคนต้องทำ','Almost everyone does it'],'meh'],[['ภาษาญี่ปุ่นไม่จำเป็น','Japanese not required'],['มีช่วยมาก ได้ค่าภาษา','A plus, with a language allowance'],'ok']],
  salary:[[['Production Engineer','Production Engineer'],28000,33000,42000,40],[['QC Inspector','QC Inspector'],18000,21000,26000,33],[['Environmental Officer','Environmental Officer'],24000,28000,34000,9],[['เจ้าหน้าที่ความปลอดภัย (จป.)','Safety Officer'],22000,26000,32000,13]],
  interview:{rounds:3,days:['2 สัปดาห์','2 weeks'],diff:'mid',qs:[['อธิบาย 5ส และ Kaizen','Explain 5S and kaizen'],['สอบวัดความถนัดเชิงช่าง','Mechanical aptitude test'],['สัมภาษณ์กับผู้จัดการชาวญี่ปุ่น','Interview with a Japanese manager']]},
  reviews:[
   {role:['Environmental Officer','Environmental Officer'],type:'emp',mood:0,r:4,t:['สายสิ่งแวดล้อมมีที่ยืน','Real room for environmental roles'],p:['ได้ดูแลระบบบำบัดน้ำเสีย ใช้ความรู้จุลชีวะจริง','Run wastewater treatment; real microbiology'],c:['ต้องเข้าไลน์ผลิตบ่อย','Often on the production floor'],d:'Q3 2026',v:true,h:19},
   {role:['Production Engineer','Production Engineer'],type:'emp',mood:1,r:3,t:['เงินดีแต่ชีวิตอยู่ที่โรงงาน','Great pay, but your life is the factory'],p:['โบนัสคุ้มมาก','Bonus is worth it'],c:['โทรตามตอนดึกเมื่อไลน์หยุด','Late-night calls when the line stops'],d:'Q2 2026',v:true,h:26}]},
 {id:'popcorn',name:['ป๊อปคอร์น ครีเอทีฟ','Popcorn Creative'],mk:['ปค','PC'],hue:'#FFF0A8',ind:'agency',size:75,loc:['ทองหล่อ','Thonglor'],transit:['BTS ทองหล่อ เดิน 5 นาที','5-min walk from BTS Thong Lo'],overall:3.5,
  cats:{pay:3.0,benefit:2.9,boss:3.8,wlb:2.7,growth:4.3,culture:4.5},mood:[40,35,25],trend:31,
  ai:{pros:[['งานสนุก ได้ทำแคมเปญแบรนด์ดัง','Fun work on big-brand campaigns'],['ออฟฟิศสวย บรรยากาศดี','Beautiful office, great vibe'],['ได้พอร์ตเร็ว','Build a portfolio fast']],
      cons:[['ลูกค้าแก้งานดึก','Late-night client revisions'],['สวัสดิการพื้นฐาน','Basic benefits only'],['เงินเดือนเริ่มต้นต่ำ','Low starting pay']]},
  reality:[[['เวลาทำงานยืดหยุ่น','Flexible hours'],['ยืดหยุ่นแต่เลิกดึก','Flexible, but late finishes'],'meh'],[['ประกันสุขภาพ','Health insurance'],['มีแค่ประกันสังคม','Social security only'],'no'],[['ปาร์ตี้ทีมทุกเดือน','Monthly team parties'],['มีจริง สนุกมาก','Real, and fun'],'ok']],
  salary:[[['Content Creator','Content Creator'],18000,22000,28000,17],[['Graphic Designer','Graphic Designer'],18000,23000,30000,21],[['Account Executive','Account Executive'],20000,25000,32000,13],[['เจ้าหน้าที่ประชาสัมพันธ์','PR Executive'],20000,23000,28000,11]],
  interview:{rounds:2,days:['1 สัปดาห์','1 week'],diff:'mid',qs:[['ส่งพอร์ตและเล่างานที่ชอบที่สุด','Walk us through your portfolio'],['ทำโจทย์ไอเดียแคมเปญใน 48 ชม.','48-hour campaign idea challenge']]},
  reviews:[
   {role:['Content Creator','Content Creator'],type:'emp',mood:0,r:4,t:['ครีเอทีฟสายเลือดต้องชอบ','Creatives will love it'],p:['ไอเดียเราได้ขึ้นจอจริง','Your ideas actually go live'],c:['ลูกค้าแก้งานตีสอง','Client edits at 2 a.m.'],d:'Q3 2026',v:true,h:29},
   {role:['Account Executive','Account Executive'],type:'emp',mood:2,r:2,t:['รับแรงกดดันจากลูกค้าเต็ม ๆ','You absorb all the client pressure'],p:['เรียนรู้การสื่อสารเยอะ','Learn a lot about communication'],c:['WLB แทบไม่มี','Barely any work-life balance'],d:'Q2 2026',v:true,h:22},
   {role:['นักศึกษาฝึกงาน','Intern'],type:'intern',mood:0,r:5,t:['ฝึกงานที่ได้งานจริงลงพอร์ต','Internship work that goes in your portfolio'],p:['พี่ ๆ ให้ลองคิดแคมเปญเอง','Seniors let you pitch ideas'],c:['ไม่มีเบี้ยเลี้ยง','No allowance'],d:'Q1 2026',v:false,h:14}]},
 {id:'pixelchang',name:['พิกเซลช้าง สตูดิโอ','Pixel Chang Studio'],mk:['พช','PX'],hue:'#D4F2C4',ind:'game',size:140,loc:['สยาม','Siam'],transit:['BTS สยาม เดิน 5 นาที','5-min walk from BTS Siam'],overall:4.2,
  cats:{pay:3.9,benefit:3.8,boss:4.3,wlb:3.9,growth:4.4,culture:4.7},mood:[70,22,8],trend:36,
  ai:{pros:[['ทีมรักเกมจริง บรรยากาศดีมาก','A team that loves games; great vibe'],['ได้ทำเกมที่คนเล่นทั่วโลก','Games played worldwide'],['มีงบซื้อเกมและอุปกรณ์','Budget for games and gear']],
      cons:[['ช่วงก่อนปล่อยเกม Crunch หนัก','Heavy crunch before launch'],['ขึ้นกับยอดเกม','Depends on game sales'],['ตำแหน่งเปิดน้อย','Few openings']]},
  reality:[[['ไม่มี Crunch','No crunch'],['มีช่วงสั้น ๆ ก่อนปล่อยเกม','Short crunch before launches'],'meh'],[['ไฮบริด','Hybrid'],['เข้าออฟฟิศ 3 วัน','3 office days'],'ok'],[['โบนัสตามยอดเกม','Bonus tied to game sales'],['ปีล่าสุด 2 เดือน','2 months last year'],'ok']],
  salary:[[['Game Designer','Game Designer'],28000,35000,48000,12],[['QA Tester','QA Tester'],18000,21000,26000,16],[['Unity Developer','Unity Developer'],35000,45000,65000,14]],
  interview:{rounds:3,days:['2 สัปดาห์','2 weeks'],diff:'mid',qs:[['วิเคราะห์เกมที่ชอบ 1 เกม','Break down a game you love'],['Test ทำเลเวลดีไซน์','Level design test'],['คุยกับทีมทั้งทีม','Meet the whole team']]},
  reviews:[
   {role:['QA Tester','QA Tester'],type:'emp',mood:0,r:5,t:['ได้เงินจากการเล่นเกม (จริงจัง)','Paid to play games (seriously)'],p:['ทีมใจดี มีเส้นทางไปเป็น Designer','Kind team, path to designer roles'],c:['เล่นด่านเดิม 200 รอบ','Replaying the same level 200 times'],d:'Q3 2026',v:true,h:45},
   {role:['Unity Developer','Unity Developer'],type:'emp',mood:0,r:4,t:['เก่งขึ้นเร็วมาก','You level up fast'],p:['Code review จริงจัง','Serious code reviews'],c:['Crunch 2 สัปดาห์ก่อนปล่อยเกม','2-week crunch pre-launch'],d:'Q2 2026',v:true,h:18}]},
 {id:'sunwave',name:['ซันเวฟ เอนเนอร์ยี','Sunwave Energy'],mk:['ซว','SW'],hue:'#FFE6A6',ind:'energy',size:1800,loc:['จตุจักร','Chatuchak'],transit:['MRT จตุจักร เดิน 5 นาที','5-min walk from MRT Chatuchak'],overall:4.1,
  cats:{pay:4.4,benefit:4.4,boss:3.7,wlb:4.0,growth:3.6,culture:3.8},mood:[60,30,10],trend:12,
  ai:{pros:[['เงินเดือนและโบนัสสูง','High pay and bonus'],['มั่นคงมาก','Very stable'],['งานพลังงานสะอาดกำลังโต','Clean energy is growing']],
      cons:[['ขั้นตอนเอกสารเยอะ','Lots of bureaucracy'],['คนรุ่นใหม่เสนอไอเดียยาก','Hard for juniors to be heard'],['บางตำแหน่งต้องไปไซต์ต่างจังหวัด','Some roles need upcountry site visits']]},
  reality:[[['โบนัส 4–6 เดือน','4–6 month bonus'],['ได้ 5 เดือน','5 months'],'ok'],[['ทำงาน 8:30–16:30','Hours 8:30–16:30'],['ตรงเวลาจริง','Really on time'],'ok'],[['นวัตกรรม','Innovation'],['ช้ากว่าที่คิด','Slower than advertised'],'meh']],
  salary:[[['Environmental Scientist','Environmental Scientist'],27000,32000,40000,15],[['Biogas Process Engineer','Biogas Process Engineer'],30000,36000,48000,8],[['Business Analyst','Business Analyst'],30000,36000,46000,13]],
  interview:{rounds:3,days:['1 เดือน','1 month'],diff:'hard',qs:[['สอบข้อเขียนความรู้ทั่วไปและภาษาอังกฤษ','General knowledge and English exam'],['อธิบายการผลิตก๊าซชีวภาพ','Explain biogas production'],['สัมภาษณ์กับคณะกรรมการ','Panel interview']]},
  reviews:[
   {role:['Biogas Process Engineer','Biogas Process Engineer'],type:'emp',mood:0,r:5,t:['จุลชีวะมาทำพลังงานได้ เงินดีด้วย','Microbiology meets energy, with great pay'],p:['ดูแลระบบหมักก๊าซชีวภาพจริง','Run real anaerobic digesters'],c:['ไปไซต์ต่างจังหวัดเดือนละครั้ง','Monthly upcountry site trips'],d:'Q3 2026',v:true,h:37},
   {role:['Business Analyst','Business Analyst'],type:'emp',mood:1,r:3,t:['มั่นคงแต่ช้า','Stable but slow'],p:['เลิกงานตรงเวลา','Leave on time'],c:['เอกสารอนุมัติหลายชั้น','Multi-level approvals'],d:'Q1 2026',v:true,h:12}]},
 {id:'bloomy',name:['บลูมมี่ บิวตี้ แล็บ','Bloomy Beauty Lab'],mk:['บม','BB'],hue:'#FFD9EC',ind:'beauty',size:350,loc:['บางเขน','Bang Khen'],transit:['BTS วัดพระศรีฯ เดิน 10 นาที','10-min walk from BTS Wat Phra Sri'],overall:4.0,
  cats:{pay:3.6,benefit:3.9,boss:4.1,wlb:4.0,growth:4.0,culture:4.3},mood:[58,31,11],trend:25,
  ai:{pros:[['ได้ทดลองสูตรเครื่องสำอางจริง','Develop real cosmetic formulas'],['ส่วนลดสินค้า 50%','50% off products'],['ทีมส่วนใหญ่เป็นคนรุ่นใหม่','Mostly young team']],
      cons:[['เงินเดือนเริ่มต้นกลาง ๆ','Average starting pay'],['ช่วงออกสินค้าใหม่เร่งงาน','Rush before launches'],['ต้องทำเอกสาร อย. เยอะ','Lots of FDA paperwork']]},
  reality:[[['ทำงาน 5 วัน','5-day week'],['5 วันจริง','Really 5 days'],'ok'],[['OT จ่ายตามกฎหมาย','OT paid by law'],['จ่ายครบ','Paid'],'ok'],[['ขึ้นเงินเดือนตามผลงาน','Merit raises'],['เฉลี่ย 5%','About 5%'],'meh']],
  salary:[[['Cosmetic QC Microbiologist','Cosmetic QC Microbiologist'],20000,23500,28000,14],[['Formulation Chemist','Formulation Chemist'],23000,27000,34000,11],[['Regulatory Officer','Regulatory Officer'],22000,26000,32000,8]],
  interview:{rounds:2,days:['1 สัปดาห์','1 week'],diff:'mid',qs:[['ทดสอบ Preservative efficacy test ทำอย่างไร','How is a preservative efficacy test done?'],['ใช้เครื่องสำอางแบรนด์ไหน ชอบเพราะอะไร','Which beauty brands do you use and why?']]},
  reviews:[
   {role:['Cosmetic QC Microbiologist','Cosmetic QC Microbiologist'],type:'emp',mood:0,r:4,t:['จุลชีวะสายความงามก็มีนะ','Yes, there’s beauty-industry microbiology'],p:['ทำ Challenge test ใช้ความรู้ตรงสาย','Challenge testing that uses your degree'],c:['ช่วงออกสินค้าใหม่ตัวอย่างเยอะ','Sample floods before launches'],d:'Q3 2026',v:true,h:31},
   {role:['นักศึกษาฝึกงาน','Intern'],type:'intern',mood:0,r:5,t:['ฝึกงานได้ของฟรีด้วย','Free products as a bonus'],p:['พี่เลี้ยงใส่ใจ มีเบี้ยเลี้ยง 350','Caring mentor, 350 THB allowance'],c:['ห้องแล็บเย็นมาก','The lab is freezing'],d:'Q2 2026',v:false,h:16}]},
 {id:'puimek',name:['ปุยเมฆ แอร์','Puimek Air'],mk:['ปม','PM'],hue:'#CFE8FF',ind:'airline',size:2400,loc:['ดอนเมือง','Don Mueang'],transit:['รถไฟฟ้าสายสีแดง ดอนเมือง เดิน 10 นาที','10-min walk from SRT Red Line Don Mueang'],overall:3.8,
  cats:{pay:3.6,benefit:4.3,boss:3.5,wlb:3.0,growth:3.9,culture:4.2},mood:[52,33,15],trend:19,
  ai:{pros:[['ตั๋วเครื่องบินพนักงานลดแรง เที่ยวได้ทั้งปี','Big staff ticket discounts, travel all year'],['ได้ใช้ภาษาอังกฤษทุกวัน','Use English every day'],['ทีมรุ่นใหม่ สนุก ช่วยกันดี','Young, fun, supportive team']],
      cons:[['ตารางงานเป็นกะ ไม่ตรงวันหยุดคนอื่น','Shift rosters that rarely match weekends'],['ช่วงเทศกาลงานหนักมาก','Very heavy workload during holidays'],['เงินเดือนฐานภาคพื้นค่อนข้างต่ำ','Fairly low base pay for ground staff']]},
  reality:[[['ตั๋วฟรีปีละ 4 ใบ','4 free tickets a year'],['ได้จริง แต่ต้องรอที่นั่งว่าง','Real, but standby only'],'meh'],[['เบี้ยเลี้ยงบิน','Flight allowance'],['จ่ายครบทุกเที่ยว','Paid in full for every flight'],'ok'],[['วันหยุด 8 วัน/เดือน','8 days off a month'],['ได้จริง แต่ถูกเรียกแทนบ่อยช่วงไฮซีซัน','Yes, but often called in during high season'],'meh'],[['ทำงานที่บ้านได้','Work from home'],['เฉพาะฝ่ายออฟฟิศบางทีม','Only some office teams'],'no']],
  salary:[[['Ground Staff (จบใหม่)','Ground Staff (new grad)'],16000,18500,22000,36],[['Cabin Crew','Cabin Crew'],25000,32000,42000,28],[['Aircraft Maintenance Technician','Aircraft Maintenance Technician'],24000,30000,40000,12],[['นักศึกษาฝึกงาน ภาคพื้น (เบี้ยเลี้ยง)','Ground intern (allowance)'],300,350,400,17,'day']],
  interview:{rounds:3,days:['2–3 สัปดาห์','2–3 weeks'],diff:'hard',qs:[['สัมภาษณ์เป็นภาษาอังกฤษและอ่านประกาศบนเครื่อง','Interview in English and read an in-flight announcement'],['ทดสอบว่ายน้ำและวัดระยะเอื้อม','Swim test and arm-reach check'],['ถ้าผู้โดยสารไม่ยอมนั่งตอนสัญญาณคาดเข็มขัดขึ้น จะทำอย่างไร','A passenger will not sit when the seatbelt sign is on. What do you do?']]},
  reviews:[
   {role:['Cabin Crew','Cabin Crew'],type:'emp',mood:0,r:4,t:['ได้เที่ยวไปด้วยทำงานไปด้วย','Work and travel at the same time'],p:['ได้ไปหลายเมือง เพื่อนร่วมงานน่ารัก','Many cities, lovely crew'],c:['ตื่นตีสามเป็นเรื่องปกติ','3 a.m. wake-ups are normal'],d:'Q3 2026',v:true,h:41},
   {role:['นักศึกษาฝึกงาน ภาคพื้น','Ground Staff Intern'],type:'intern',mood:0,r:5,t:['ฝึกงานที่เคาน์เตอร์เช็กอินได้ลงมือจริง','Real hands-on work at check-in'],p:['พี่เลี้ยงสอนระบบเช็กอินตั้งแต่วันแรก มีเบี้ยเลี้ยง','Mentor taught the check-in system from day one, with an allowance'],c:['ยืนนานทั้งกะ','Standing the whole shift'],d:'Q2 2026',v:true,h:19},
   {role:['Aircraft Maintenance Technician','Aircraft Maintenance Technician'],type:'emp',mood:1,r:3,t:['งานละเอียด ความรับผิดชอบสูง','Precise work, big responsibility'],p:['ได้ใบรับรองและอบรมต่อเนื่อง','Certifications and ongoing training'],c:['กะดึกในโรงซ่อมบ่อย','Frequent night shifts in the hangar'],d:'Q1 2026',v:true,h:14},
   {role:['Ground Staff','Ground Staff'],type:'emp',mood:2,r:2,t:['ช่วงเทศกาลโหดมาก','Holiday season is brutal'],p:['ส่วนลดตั๋วดีจริง','Ticket discounts are great'],c:['ถูกเรียกแทนกะกะทันหันบ่อย ลาพักยาก','Often called in last minute, hard to get leave'],d:'Q4 2025',v:false,h:10,reply:['ขอบคุณสำหรับความเห็นค่ะ เราเพิ่มพนักงานสำรองช่วงเทศกาลและปรับระบบแลกกะให้ขอล่วงหน้าได้แล้ว — ทีม HR','Thank you for the feedback. We added standby staff for holidays and now let you request shift swaps in advance. — HR team']}]},
];
const TAGS=[['ฝึกงาน','Internship'],['เงินเดือน','Salary'],['หัวหน้า','Boss'],['ลาออก','Resigning'],['สัมภาษณ์','Interview'],['ชีวิตทำงาน','Work life']];
const POSTS=[
 {id:'p1',kind:'ask',tag:0,by:['นักจุลน้อย #12','Little Microbe #12'],ava:'🦠',bg:'#BDEBDD',ts:95,likes:24,text:['ปี 3 จุลชีวะค่ะ เทอมหน้าจะไปฝึกงาน QC โรงงานอาหาร ต้องเตรียมตัวเรื่องอะไรบ้าง? กลัวทำอะไรไม่เป็นเลย 😭','3rd-year microbiology here. I start a QC internship at a food factory next term. How should I prepare? I’m scared I won’t know anything 😭'],
  comments:[{by:['พี่มิ้นท์','Mint'],ava:'🧪',bg:'#FFE08A',ver:true,lv:'senior',ts:80,likes:31,text:['ทบทวน Aseptic technique การนับโคโลนี และ HACCP เบื้องต้น แค่นี้ก็รอดแล้ว พี่เลี้ยงส่วนใหญ่สอนใหม่หมดอยู่แล้ว ไม่ต้องกลัว','Review aseptic technique, colony counting and basic HACCP. That gets you through. Most mentors teach from scratch anyway.']},
   {by:['คนแล็บตัวจริง','Real Lab Person'],ava:'🔬',bg:'#C9DBFF',ver:false,ts:60,likes:12,text:['ฝึกจดบันทึกให้ละเอียด งาน QC คือเอกสารครึ่งหนึ่ง ถือสมุดเล็ก ๆ ติดตัวไว้เลย','Practice detailed notes. Half of QC is documentation. Carry a small notebook.']}]},
 {id:'p2',kind:'share',tag:1,by:['สายยาเงินดี','Pharma Pays'],ava:'💊',bg:'#C9DBFF',ver:true,lv:'senior',ts:300,likes:88,text:['แชร์ประสบการณ์ต่อรองเงินเดือนครั้งแรก 💸 บริษัทเสนอ 25,000 ผมขอ 28,000 พร้อมเหตุผลว่ามีประสบการณ์ฝึกงานในคลีนรูม สุดท้ายได้ 27,500 ครับ สิ่งที่ช่วยคือดูข้อมูลเงินเดือนตำแหน่งเดียวกันก่อนไปคุย','My first salary negotiation 💸 They offered 25,000; I asked for 28,000, citing my cleanroom internship. Ended at 27,500. Checking salary data for the role beforehand made all the difference.'],
  comments:[{by:['เด็กจบใหม่ 2026','Class of 2026'],ava:'🎓',bg:'#FFD3E2',ts:250,likes:9,text:['ขอบคุณมากครับ ไม่เคยกล้าต่อรองเลย ครั้งหน้าจะลองดู','Thank you! I never dared to negotiate. I’ll try next time.']},
   {by:['พี่นัท','Nut'],ava:'🎯',bg:'#D9D3FF',ver:true,lv:'expert',ts:200,likes:40,text:['ในฐานะ Recruiter บอกเลยว่าการต่อรองแบบมีเหตุผลแบบนี้ ไม่มีบริษัทไหนมองไม่ดีครับ 👍','Speaking as a recruiter: negotiating with reasons like this never looks bad. 👍']},
   {by:['QA สาวออฟฟิศ','Office QA'],ava:'📋',bg:'#FFE3B8',ts:120,likes:5,text:['ขอถามต่อ ถ้าบริษัทบอกว่าเป็นเรทตายตัวต้องทำยังไงคะ','Follow-up: what if they say the rate is fixed?']}]},
 {id:'p3',kind:'ask',tag:2,by:['พนักงานจบใหม่','New Grad Employee'],ava:'😵',bg:'#FFE3E8',ts:40,likes:56,text:['หัวหน้าสั่งงานใน LINE ตอนสี่ทุ่มแทบทุกวัน แบบนี้ปกติไหม? ไม่ตอบก็กลัวโดนเพ่งเล็ง','My boss sends work on LINE at 10 p.m. almost every day. Is that normal? I’m afraid of being singled out if I don’t reply.'],
  comments:[{by:['พี่โอม','Ohm'],ava:'🤝',bg:'#DDF0B5',ver:true,lv:'expert',ts:30,likes:47,text:['ไม่ควรเป็นเรื่องปกติครับ ลองคุยตกลงเวลาตอบข้อความกับหัวหน้า ถ้าเป็นงานนอกเวลาควรนับเป็น OT','It shouldn’t be. Agree on reply hours with your boss; after-hours work should count as OT.']},
   {by:['เคยเจอเหมือนกัน','Been There'],ava:'🙃',bg:'#E4F0FD',ts:22,likes:18,text:['เคยเจอ! ลองตั้งปิดแจ้งเตือนหลังสองทุ่ม แล้วตอบตอนเช้าแบบสุภาพ หัวหน้าเริ่มปรับตัวเองเลย','Same here! I muted alerts after 8 p.m. and replied politely in the morning. My boss adjusted.']}]},
 {id:'p4',kind:'share',tag:5,by:['มนุษย์ออฟฟิศปีแรก','First-year Office Human'],ava:'☕',bg:'#FFE08A',ts:720,likes:132,text:['5 อย่างที่อยากบอกตัวเองก่อนเริ่มงานวันแรก\n1) จดชื่อคนในทีมให้ครบ\n2) ถามได้ ไม่มีใครว่า\n3) อย่ารับงานเกินตัวเพราะเกรงใจ\n4) เก็บสลิปเงินเดือนทุกเดือน\n5) พักเที่ยงให้เป็นพักเที่ยงจริง ๆ','5 things I wish I’d known before day one\n1) Write down everyone’s name\n2) Asking questions is fine\n3) Don’t take on too much just to be polite\n4) Keep every payslip\n5) Make your lunch break a real break'],
  comments:[{by:['นักจุลน้อย #12','Little Microbe #12'],ava:'🦠',bg:'#BDEBDD',ts:600,likes:7,text:['ข้อ 3 โดนมาก 😂','Number 3 hits hard 😂']}]},
 {id:'p5',kind:'ask',tag:3,by:['คิดหนักมาก','Overthinking'],ava:'🌧️',bg:'#E4F0FD',ts:1440,likes:41,text:['อยู่มา 8 เดือน งานไม่ตรงสายเลย อยากลาออกแต่กลัวเรซูเม่ดูไม่ดี ควรทนให้ครบปีไหม?','8 months in and the job isn’t my field at all. I want to quit but worry it’ll look bad on my resume. Should I stick it out for a year?'],
  comments:[{by:['พี่แพร','Prae'],ava:'📊',bg:'#FFD0BE',ver:true,lv:'senior',ts:1300,likes:29,text:['หางานใหม่ให้ได้ก่อนแล้วค่อยยื่นลาออก 8 เดือนอธิบายได้ ถ้าเล่าได้ว่าเรียนรู้อะไรและทำไมถึงย้าย','Line up a new job first, then resign. 8 months is explainable if you can say what you learned and why you’re moving.']}]},
 {id:'p6',kind:'ask',tag:4,by:['ใกล้สัมภาษณ์แล้ว','Interview Soon'],ava:'😬',bg:'#FFD3E2',ts:10,likes:6,text:['พรุ่งนี้สัมภาษณ์งาน ถ้าโดนถามว่า “จุดอ่อนของคุณคืออะไร” ควรตอบยังไงดีคะ?','Interview tomorrow. How should I answer “What’s your weakness?”'],comments:[]},
];
const LV={senior:['รุ่นพี่','Senior'],expert:['ผู้เชี่ยวชาญ','Expert']};
const POLL={q:['วันนี้คุณเลิกงานกี่โมง?','What time did you finish work today?'],o:[[['ก่อน 17:00','Before 17:00'],18],[['17:00–18:00','17:00–18:00'],41],[['18:00–20:00','18:00–20:00'],29],[['หลัง 20:00 😵','After 20:00 😵'],12]]};
const QUIZ=[
 {q:['วันทำงานในฝันของคุณเป็นแบบไหน?','What does your dream workday look like?'],o:[[['เข้าออฟฟิศบ้าง ทำที่บ้านบ้าง','Some office, some home'],'flex'],[['ได้ลงมือในแล็บหรือหน้างานทั้งวัน','Hands-on in the lab or field all day'],'hands'],[['ระบบชัด มีขั้นตอนแน่นอน','Clear systems and set procedures'],'stable']]},
 {q:['อะไรสำคัญที่สุดตอนเลือกงาน?','What matters most when choosing a job?'],o:[[['เงินเดือนและโบนัส','Salary and bonus'],'stable'],[['ได้เรียนรู้เร็ว','Learning fast'],'flex'],[['ทีมและบรรยากาศ','Team and atmosphere'],'hands']]},
 {q:['ถ้าต้องทำ OT บ่อย คุณ…','If you often had to work overtime, you would…'],o:[[['โอเค ถ้าจ่ายครบ','Be fine if it is paid'],'stable'],[['ขอยืดหยุ่นเวลาแทน','Ask for flexible hours instead'],'flex'],[['ได้ ถ้างานสนุก','Be fine if the work is fun'],'hands']]},
 {q:['ที่ทำงานอยู่ไกลเมือง แต่มีหอพักให้','The job is far from the city but comes with housing'],o:[[['ไม่เอา ขอใกล้รถไฟฟ้า','No thanks, I want to be near the train'],'flex'],[['ได้เลย ถ้างานตรงใจ','Sure, if the work fits me'],'hands'],[['ถ้ามีรถรับส่งก็โอเค','Fine if there is a shuttle'],'stable']]},
 {q:['องค์กรขนาดไหนที่คุณชอบ?','What size of organization do you prefer?'],o:[[['สตาร์ทอัพ ทีมเล็ก คล่องตัว','A small, nimble startup'],'flex'],[['ใหญ่และมั่นคง','Large and stable'],'stable'],[['ขนาดกลาง ใกล้ชิดเจ้าของ','Mid-sized, close to the owner'],'hands']]},
];
const QRES={
 flex:{t:['สายคล่องตัว','The Flexible One'],d:['คุณเหมาะกับที่ทำงานยืดหยุ่น เรียนรู้เร็ว และให้พื้นที่คุณได้เสนอไอเดีย','You thrive where work is flexible, learning is fast and your ideas are heard.'],co:['cloudbun','pixelchang','popcorn']},
 hands:{t:['สายลงมือทำ','The Hands-on One'],d:['คุณมีความสุขเมื่อได้จับงานจริง ทีมเล็ก และเห็นผลงานของตัวเองชัด ๆ','You are happiest doing real work in a small team where your results show.'],co:['greencap','bloomy','wellness']},
 stable:{t:['สายมั่นคง','The Steady One'],d:['คุณชอบระบบชัดเจน เงินเดือนดี และสวัสดิการที่วางแผนชีวิตได้','You like clear systems, good pay and benefits you can plan your life around.'],co:['northstar','srisiam','sunwave']},
};
const MOODS=[['😊',['อยู่ยาว','Staying'],'good'],['😐',['พอไหว','It’s OK'],'mid'],['😵',['หนีด่วน','Run!'],'bad']];

/* ---------- career map (แผนที่อาชีพ): faculty → 7 worlds → groups → roles → role page ----------
   Sample guidance data only (labelled "ข้อมูลแนะนำเบื้องต้น"). Fit levels: d = direct 🟢, b = can cross over 🟡, s = needs new skills 🟠.
   Skills in common between a faculty (+ major) and a role are "skills you already have"; the rest are "skills to add" with a rough time. */
const SK={lab:['งานแล็บพื้นฐาน','Basic lab work',3],micro:['เทคนิคจุลชีววิทยา','Microbiology techniques',4],chem:['เคมีวิเคราะห์','Analytical chemistry',4],gmp:['GMP / HACCP / ISO','GMP / HACCP / ISO',1],
 stat:['สถิติ','Statistics',2],excel:['Excel ขั้นสูง','Advanced Excel',1],sql:['SQL','SQL',2],python:['Python','Python',3],viz:['Power BI / Tableau','Power BI / Tableau',1],code:['เขียนโปรแกรม','Programming',6],test:['ทดสอบซอฟต์แวร์','Software testing',2],
 figma:['Figma / UX','Figma / UX',3],design:['ออกแบบกราฟิก','Graphic design',4],writing:['เขียนคอนเทนต์','Content writing',1],video:['ตัดต่อวิดีโอ','Video editing',2],mkt:['การตลาดดิจิทัล','Digital marketing',2],
 sales:['การขายและเจรจา','Sales & negotiation',2],present:['การนำเสนอ','Presenting',1],english:['ภาษาอังกฤษสื่อสาร','Business English',3],service:['บริการลูกค้า','Customer service',1],acct:['บัญชีและงบการเงิน','Accounting',6],
 finance:['วิเคราะห์การเงิน','Financial analysis',3],scm:['ซัพพลายเชน','Supply chain basics',2],research:['วิจัยและออกแบบการทดลอง','Research & experiments',4],formul:['ตั้งสูตรผลิตภัณฑ์','Product formulation',4],
 process:['กระบวนการผลิต','Production processes',4],cad:['CAD / เขียนแบบ','CAD drafting',3],care:['ดูแลผู้ป่วย','Patient care',12],license:['ใบประกอบวิชาชีพ','Professional licence',12],teach:['เทคนิคการสอน','Teaching methods',6],
 psych:['จิตวิทยาและการเข้าใจคน','Psychology & people skills',3],law:['กฎหมาย','Law',12],reg:['กฎระเบียบ อย. และมาตรฐาน','Regulations & standards',2],env:['สิ่งแวดล้อมและน้ำเสีย','Environment & wastewater',3],
 safety:['ความปลอดภัยในการทำงาน (จป.)','Workplace safety (OSH)',2],game:['เกมดีไซน์','Game design',4],unity:['Unity / C#','Unity / C#',4],plan:['วางแผนและจัดการงาน','Planning & organising',1],docs:['เขียนรายงานและเอกสาร','Reports & documentation',1],
 lang:['ภาษาที่ 3 (จีน/ญี่ปุ่น)','A third language',6],policy:['วิเคราะห์นโยบาย','Policy analysis',3],hr:['งาน HR และสรรหา','HR & recruiting',2]};
/* faculties: emoji, name, skills the faculty usually builds, majors {id:[name, extra skills, roles that are a direct fit for this major]} */
const FAC={
 sci:{e:'🔬',n:['วิทยาศาสตร์','Science'],has:['lab','chem','micro','stat','research','docs'],mj:{micro:[['จุลชีววิทยา','Microbiology'],['micro'],['qcmicro']],chem:[['เคมี','Chemistry'],['chem'],['qc','formchem']],phys:[['ฟิสิกส์','Physics'],['stat','code'],[]],bio:[['ชีววิทยา','Biology'],['micro'],[]],cs:[['วิทยาการคอมพิวเตอร์','Computer science'],['code','sql','python','test'],['swe','da','qatest']],math:[['คณิตศาสตร์','Mathematics'],['stat','python'],['da']],stat:[['สถิติ','Statistics'],['stat','sql','excel'],['da','ba']],envsci:[['วิทยาศาสตร์สิ่งแวดล้อม','Environmental science'],['env'],['envoff']],biotech:[['เทคโนโลยีชีวภาพ','Biotechnology'],['micro','process'],['ferm']]}},
 eng:{e:'⚙️',n:['วิศวกรรมศาสตร์','Engineering'],has:['process','cad','plan','excel','safety','stat'],mj:{civil:[['วิศวกรรมโยธา','Civil engineering'],['cad'],[]],mech:[['วิศวกรรมเครื่องกล','Mechanical engineering'],['cad'],['maint']],elec:[['วิศวกรรมไฟฟ้า','Electrical engineering'],[],[]],cpe:[['วิศวกรรมคอมพิวเตอร์','Computer engineering'],['code','sql','test'],['swe','qatest']],ie:[['วิศวกรรมอุตสาหการ','Industrial engineering'],['scm'],['scm']],cheme:[['วิศวกรรมเคมี','Chemical engineering'],['chem','env'],['processeng']],enve:[['วิศวกรรมสิ่งแวดล้อม','Environmental engineering'],['env'],['envoff']]}},
 agro:{e:'🌾',n:['อุตสาหกรรมเกษตร / เกษตร','Agro-industry / Agriculture'],has:['lab','micro','gmp','formul','process','research'],mj:{foodsci:[['วิทยาศาสตร์และเทคโนโลยีการอาหาร','Food science & technology'],['docs'],['rdfood','qa']],agri:[['เกษตรศาสตร์','Agriculture'],['plan'],[]],agbio:[['เทคโนโลยีชีวภาพเกษตร','Agricultural biotechnology'],[],['ferm']],foodbiz:[['ธุรกิจอาหาร','Food business'],['mkt','sales'],['cat']]}},
 health:{e:'🩺',n:['สหเวช / พยาบาล / สาธารณสุข','Allied health / Nursing / Public health'],has:['lab','micro','care','docs','service','license'],mj:{medtech:[['เทคนิคการแพทย์','Medical technology'],[],['medtech']],nurse:[['พยาบาลศาสตร์','Nursing'],[],['nurse']],pubhealth:[['สาธารณสุขศาสตร์','Public health'],['safety','env'],['safety']],physio:[['กายภาพบำบัด','Physical therapy'],['psych'],[]]}},
 pharm:{e:'💊',n:['เภสัชศาสตร์','Pharmacy'],has:['chem','gmp','reg','license','lab','docs'],mj:{pharmcare:[['เภสัชกรรมบริบาล','Pharmaceutical care'],['care'],['pharmacist']],pharmsci:[['วิทยาศาสตร์เภสัชกรรม','Pharmaceutical sciences'],['formul'],['formchem']]}},
 bus:{e:'📈',n:['บริหารธุรกิจ','Business administration'],has:['excel','mkt','present','plan','sales','scm'],mj:{mkt:[['การตลาด','Marketing'],['writing'],['mkt']],fin:[['การเงิน','Finance'],['finance'],['credit']],mgmt:[['การจัดการ','Management'],['hr'],[]],hrm:[['การจัดการทรัพยากรมนุษย์','Human resource management'],['hr','psych'],['hr']],log:[['โลจิสติกส์','Logistics'],['scm'],['scm']],ib:[['ธุรกิจระหว่างประเทศ','International business'],['english'],[]],bis:[['ระบบสารสนเทศทางธุรกิจ','Business information systems'],['sql'],['ba']]}},
 acc:{e:'🧾',n:['บัญชี','Accounting'],has:['acct','finance','excel','docs'],mj:{acc:[['การบัญชี','Accounting'],[],[]],audit:[['การสอบบัญชี','Auditing'],['reg'],['compliance']]}},
 econ:{e:'💹',n:['เศรษฐศาสตร์','Economics'],has:['stat','excel','finance','policy','present'],mj:{econ:[['เศรษฐศาสตร์','Economics'],[],[]],bizecon:[['เศรษฐศาสตร์ธุรกิจ','Business economics'],['sql'],['ba']]}},
 comm:{e:'🎬',n:['นิเทศศาสตร์','Communication arts'],has:['writing','video','mkt','present','design'],mj:{ad:[['การโฆษณา','Advertising'],['sales'],['ae']],pr:[['การประชาสัมพันธ์','Public relations'],['english'],['pr']],journ:[['วารสารศาสตร์','Journalism'],['docs'],[]],film:[['ภาพยนตร์','Film'],[],[]],digital:[['สื่อดิจิทัล','Digital media'],['figma'],['graphic']]}},
 arts:{e:'📚',n:['อักษรศาสตร์ / มนุษยศาสตร์','Arts / Humanities'],has:['english','writing','lang','present','docs'],mj:{english:[['ภาษาอังกฤษ','English'],[],[]],chinese:[['ภาษาจีน','Chinese'],[],[]],japanese:[['ภาษาญี่ปุ่น','Japanese'],[],[]],thai:[['ภาษาไทย','Thai'],[],[]],info:[['สารสนเทศศาสตร์ / บรรณารักษ์','Information science / Library'],['sql'],[]],hist:[['ประวัติศาสตร์','History'],['research'],[]]}},
 soc:{e:'🏛️',n:['รัฐศาสตร์ / สังคมศาสตร์','Political & social sciences'],has:['policy','writing','docs','present','psych'],mj:{pol:[['รัฐศาสตร์','Political science'],[],['civil','policy']],socio:[['สังคมวิทยา','Sociology'],['research'],[]],psy:[['จิตวิทยา','Psychology'],[],['hr']],ir:[['ความสัมพันธ์ระหว่างประเทศ','International relations'],['english'],[]]}},
 law:{e:'⚖️',n:['นิติศาสตร์','Law'],has:['law','reg','docs','writing','present'],mj:{law:[['นิติศาสตร์','Law'],[],[]]}},
 edu:{e:'🍎',n:['ครุศาสตร์ / ศึกษาศาสตร์','Education'],has:['teach','present','psych','license','writing'],mj:{early:[['การศึกษาปฐมวัย','Early childhood'],[],[]],scied:[['วิทยาศาสตร์ศึกษา','Science education'],['lab'],[]],englished:[['ภาษาอังกฤษศึกษา','English education'],['english'],[]],edtech:[['เทคโนโลยีการศึกษา','Educational technology'],['figma','video'],['instr']],counsel:[['จิตวิทยาการแนะแนว','Guidance & counselling'],['hr'],[]]}},
 arch:{e:'📐',n:['สถาปัตย์ / ศิลปกรรม','Architecture / Fine & applied arts'],has:['design','cad','figma','present'],mj:{arch:[['สถาปัตยกรรม','Architecture'],['plan'],[]],product:[['ออกแบบผลิตภัณฑ์','Product design'],['research'],[]],commdes:[['นิเทศศิลป์','Communication design'],['mkt'],['graphic','uxui']],fineart:[['ศิลปะ','Fine arts'],[],[]],interior:[['ออกแบบภายใน','Interior design'],[],[]]}},
 tour:{e:'✈️',n:['การท่องเที่ยวและการโรงแรม','Tourism & hospitality'],has:['service','english','lang','safety','plan'],mj:{hotel:[['การโรงแรม','Hotel management'],[],['fo']],tourism:[['การท่องเที่ยว','Tourism'],['mkt'],[]],aviation:[['ธุรกิจการบิน','Aviation business'],[],['ground','crew']],event:[['การจัดการอีเวนต์ (MICE)','Events (MICE)'],['sales'],[]]}}};
/* 7 worlds (the big circles), each drawn in a theme color token */
const WORLDS=[['scih','🧪',['วิทย์และสุขภาพ','Science & health'],'--good'],['tech','💻',['ข้อมูลและเทค','Data & tech'],'--blue'],['biz','📊',['ธุรกิจและการขาย','Business & sales'],'--orange'],['crea','🎨',['ครีเอทีฟและสื่อ','Creative & media'],'--plus-c'],['serv','🛎️',['บริการและท่องเที่ยว','Service & travel'],'--mid'],['edu','🌱',['การศึกษาและพัฒนาคน','Education & people'],'--plus-b'],['gov','🏛️',['ภาครัฐและมาตรฐาน','Public sector & standards'],'--ink-2']];
const GROUPS={lab:['scih','🔬',['แล็บและควบคุมคุณภาพ','Lab & quality control']],rnd:['scih','🧫',['วิจัยและพัฒนาผลิตภัณฑ์','R&D & product development']],care:['scih','🩺',['สุขภาพและคลินิก','Health & clinical']],plant:['scih','🏭',['โรงงานและวิศวกรรม','Plants & engineering']],
 data:['tech','📊',['วิเคราะห์ข้อมูล','Data analysis']],dev:['tech','👩‍💻',['พัฒนาซอฟต์แวร์และเกม','Software & game development']],prod:['tech','🧩',['โปรดักต์และ UX','Product & UX']],
 sales:['biz','🤝',['การตลาดและการขาย','Marketing & sales']],fin:['biz','💰',['การเงินและบัญชี','Finance & accounting']],ops:['biz','🚚',['ซัพพลายเชนและค้าปลีก','Supply chain & retail']],
 content:['crea','🎥',['คอนเทนต์และประชาสัมพันธ์','Content & PR']],design:['crea','🖌️',['ออกแบบและเกม','Design & games']],
 hotel:['serv','🏨',['โรงแรมและอาหาร','Hotels & F&B']],air:['serv','🛫',['สายการบิน','Airlines']],cx:['serv','💬',['ดูแลลูกค้า','Customer care']],
 teach:['edu','📖',['สอนและสื่อการเรียนรู้','Teaching & learning design']],people:['edu','🧑‍🤝‍🧑',['HR และพัฒนาบุคลากร','HR & people development']],
 reg:['gov','📜',['มาตรฐานและกฎหมาย','Standards & law']],envs:['gov','🌿',['สิ่งแวดล้อมและความปลอดภัย','Environment & safety']],pub:['gov','🏢',['ราชการและนโยบาย','Government & policy']]};
/* roles: group, name, skills used, salary-row names in CO (English), related job ids */
const ROLES={
 qc:{g:'lab',n:['นักวิเคราะห์ QC','QC Analyst'],u:['lab','chem','gmp','docs'],sal:['QC Analyst (new grad)','Lab Analyst (new grad)','QC Inspector'],jobs:['j5']},
 qcmicro:{g:'lab',n:['นักจุลชีววิทยา QC','QC Microbiologist'],u:['micro','lab','gmp','docs'],sal:['QC Microbiologist','Microbiologist','Cosmetic QC Microbiologist','Clinical Microbiologist'],jobs:['j3','j2','j6','j10','j17']},
 qa:{g:'lab',n:['เจ้าหน้าที่ประกันคุณภาพ (QA)','QA Officer'],u:['gmp','docs','plan','present'],sal:['QA Officer','Fresh Food QA'],jobs:['j7']},
 rdfood:{g:'rnd',n:['นักวิจัยพัฒนาผลิตภัณฑ์อาหาร','R&D Food Scientist'],u:['research','formul','lab','present'],sal:['R&D Food Scientist'],jobs:['j8']},
 formchem:{g:'rnd',n:['นักเคมีตั้งสูตร','Formulation Chemist'],u:['chem','formul','research','reg'],sal:['Formulation Chemist'],jobs:[]},
 ferm:{g:'rnd',n:['เจ้าหน้าที่งานหมัก','Fermentation Technician'],u:['micro','process','lab','gmp'],sal:['Fermentation Technician'],jobs:['j4']},
 medtech:{g:'care',n:['นักเทคนิคการแพทย์','Medical Technologist'],u:['lab','micro','license','docs'],sal:['Medical Technologist'],jobs:[]},
 nurse:{g:'care',n:['พยาบาลวิชาชีพ','Registered Nurse'],u:['care','license','service','docs'],sal:['Registered Nurse'],jobs:[]},
 pharmacist:{g:'care',n:['เภสัชกร','Pharmacist'],u:['license','reg','chem','gmp'],sal:['Production Pharmacist'],jobs:[]},
 prodeng:{g:'plant',n:['วิศวกรฝ่ายผลิต','Production Engineer'],u:['process','cad','plan','excel'],sal:['Production Engineer'],jobs:[]},
 processeng:{g:'plant',n:['วิศวกรกระบวนการ','Process Engineer'],u:['process','chem','env','excel'],sal:['Biogas Process Engineer'],jobs:['j16']},
 validation:{g:'plant',n:['เจ้าหน้าที่ Validation','Validation Officer'],u:['gmp','docs','stat','process'],sal:['Validation Officer'],jobs:[]},
 maint:{g:'plant',n:['ช่างซ่อมบำรุงอากาศยาน','Aircraft Maintenance Technician'],u:['process','license','safety','english'],sal:['Aircraft Maintenance Technician'],jobs:[]},
 da:{g:'data',n:['นักวิเคราะห์ข้อมูล','Data Analyst'],u:['sql','python','viz','stat'],sal:['Data Analyst'],jobs:['j1']},
 ba:{g:'data',n:['นักวิเคราะห์ธุรกิจ','Business Analyst'],u:['excel','sql','present','plan'],sal:['Business Analyst'],jobs:[]},
 swe:{g:'dev',n:['นักพัฒนาซอฟต์แวร์','Software Engineer'],u:['code','test','sql','english'],sal:['Software Engineer'],jobs:[]},
 gamedev:{g:'dev',n:['นักพัฒนาเกม','Game Developer'],u:['unity','code','game','test'],sal:['Unity Developer'],jobs:[]},
 qatest:{g:'dev',n:['นักทดสอบซอฟต์แวร์','QA Tester'],u:['test','docs','english'],sal:['QA Tester'],jobs:['j15']},
 uxui:{g:'prod',n:['นักออกแบบ UX/UI','Product Designer (UX/UI)'],u:['figma','research','present','design'],sal:['Product Designer'],jobs:[]},
 pm:{g:'prod',n:['ผู้จัดการผลิตภัณฑ์','Product Manager'],u:['plan','research','present','figma'],sal:['Product Manager'],jobs:[]},
 mkt:{g:'sales',n:['เจ้าหน้าที่การตลาด','Marketing Executive'],u:['mkt','writing','excel','present'],sal:['Marketing Executive'],jobs:[]},
 sales:{g:'sales',n:['เจ้าหน้าที่ฝ่ายขาย','Sales Executive'],u:['sales','present','service','english'],sal:['Sales Executive','Relationship Manager'],jobs:[]},
 ae:{g:'sales',n:['Account Executive (เอเจนซี่)','Account Executive'],u:['sales','present','plan','mkt'],sal:['Account Executive'],jobs:[]},
 credit:{g:'fin',n:['นักวิเคราะห์สินเชื่อ','Credit Analyst'],u:['finance','excel','acct','docs'],sal:['Credit Analyst'],jobs:[]},
 mt:{g:'fin',n:['Management Trainee','Management Trainee'],u:['present','plan','excel','english'],sal:['Management Trainee'],jobs:['j9']},
 acct:{g:'fin',n:['นักบัญชี','Accountant'],u:['acct','excel','docs','finance'],sal:['Accountant'],jobs:[]},
 scm:{g:'ops',n:['นักวิเคราะห์ซัพพลายเชน','Supply Chain Analyst'],u:['scm','excel','plan','sql'],sal:['Supply Chain Analyst','Transport Planner','Warehouse Supervisor'],jobs:['j11']},
 cat:{g:'ops',n:['นักวิเคราะห์หมวดสินค้า','Category Analyst'],u:['excel','mkt','scm','present'],sal:['Category Analyst'],jobs:[]},
 storemgr:{g:'ops',n:['ผู้จัดการสาขา','Store Manager'],u:['service','plan','sales','hr'],sal:['Store Manager'],jobs:[]},
 content:{g:'content',n:['คอนเทนต์ครีเอเตอร์','Content Creator'],u:['writing','video','mkt','present'],sal:['Content Creator'],jobs:['j14']},
 pr:{g:'content',n:['เจ้าหน้าที่ประชาสัมพันธ์','PR Executive'],u:['writing','present','english','mkt'],sal:['PR Executive'],jobs:[]},
 graphic:{g:'design',n:['กราฟิกดีไซเนอร์','Graphic Designer'],u:['design','mkt','present'],sal:['Graphic Designer'],jobs:[]},
 gamedesign:{g:'design',n:['เกมดีไซเนอร์','Game Designer'],u:['game','design','writing','present'],sal:['Game Designer'],jobs:[]},
 fo:{g:'hotel',n:['พนักงานต้อนรับส่วนหน้า','Front Office / Guest Service'],u:['service','english','lang','docs'],sal:['Front Office Agent','Guest Service Agent'],jobs:[]},
 hyg:{g:'hotel',n:['เจ้าหน้าที่สุขาภิบาลอาหาร','F&B Hygiene Officer'],u:['gmp','micro','docs','service'],sal:['F&B Hygiene Officer'],jobs:['j12']},
 ground:{g:'air',n:['พนักงานภาคพื้น','Ground Staff'],u:['service','english','lang','safety'],sal:['Ground Staff (new grad)'],jobs:['j18']},
 crew:{g:'air',n:['พนักงานต้อนรับบนเครื่องบิน','Cabin Crew'],u:['service','english','safety','lang'],sal:['Cabin Crew'],jobs:[]},
 cs:{g:'cx',n:['Customer Success','Customer Success'],u:['service','english','excel','writing'],sal:['Customer Success'],jobs:[]},
 teacher:{g:'teach',n:['ครู / ติวเตอร์','Teacher / Tutor'],u:['teach','license','present','psych'],sal:[],jobs:[]},
 instr:{g:'teach',n:['นักออกแบบสื่อการเรียนรู้','Instructional Designer'],u:['teach','writing','design','present'],sal:[],jobs:[]},
 hr:{g:'people',n:['เจ้าหน้าที่ HR / สรรหา','HR Officer / Recruiter'],u:['hr','psych','docs','english'],sal:['HR Officer'],jobs:[]},
 ld:{g:'people',n:['เจ้าหน้าที่พัฒนาบุคลากร','Learning & Development Officer'],u:['teach','present','psych','hr'],sal:['Learning & Development Officer'],jobs:[]},
 regaff:{g:'reg',n:['เจ้าหน้าที่ขึ้นทะเบียน อย.','Regulatory Affairs Officer'],u:['reg','docs','chem','english'],sal:['Regulatory Officer'],jobs:[]},
 legal:{g:'reg',n:['นิติกร','Legal Officer'],u:['law','docs','english','reg'],sal:['Legal Officer'],jobs:[]},
 compliance:{g:'reg',n:['เจ้าหน้าที่กำกับดูแล','Compliance Officer'],u:['reg','law','docs','finance'],sal:['Compliance Officer'],jobs:[]},
 envoff:{g:'envs',n:['เจ้าหน้าที่สิ่งแวดล้อม','Environmental Officer'],u:['env','chem','docs','safety'],sal:['Environmental Officer','Environmental Scientist'],jobs:['j13']},
 safety:{g:'envs',n:['เจ้าหน้าที่ความปลอดภัย (จป.)','Safety Officer'],u:['safety','docs','process','present'],sal:['Safety Officer'],jobs:[]},
 civil:{g:'pub',n:['เจ้าหน้าที่รัฐ / ข้าราชการ','Government Officer'],u:['docs','policy','law','present'],sal:[],jobs:[]},
 policy:{g:'pub',n:['นักวิเคราะห์นโยบาย','Policy Analyst'],u:['policy','stat','writing','present'],sal:[],jobs:[]}};
/* faculty → role → fit (the mapping table). Every faculty has 8+ roles and 3+ that cross over. */
const FIT_SRC={
 sci:'qc:d qcmicro:d formchem:d rdfood:b ferm:b validation:b regaff:b envoff:b da:b medtech:s qatest:s uxui:s teacher:s content:s',
 eng:'prodeng:d processeng:d maint:d validation:d safety:d envoff:b swe:b da:b scm:b ba:b mt:b pm:s gamedev:s sales:s',
 agro:'rdfood:d qa:d qc:d ferm:d hyg:d qcmicro:b formchem:b regaff:b cat:b sales:b scm:s content:s',
 health:'medtech:d nurse:d qcmicro:b qc:b hyg:b regaff:b sales:b cs:b safety:b da:s teacher:s',
 pharm:'pharmacist:d regaff:d validation:d formchem:b qc:b qa:b sales:b pm:s content:s da:s',
 bus:'mkt:d sales:d mt:d scm:d cat:d storemgr:d ba:b hr:b ae:b content:b cs:b da:s pm:s',
 acc:'acct:d credit:d compliance:b ba:b mt:b scm:b da:s sales:s',
 econ:'credit:d ba:d policy:d da:b mt:b scm:b cat:b compliance:b civil:b mkt:s',
 comm:'content:d pr:d mkt:d ae:d graphic:b cs:b instr:b hr:s uxui:s gamedesign:s',
 arts:'content:d cs:d pr:b fo:b ground:b crew:b teacher:b instr:b hr:b mkt:s uxui:s',
 soc:'civil:d policy:d hr:d pr:b cs:b content:b compliance:b ld:b mkt:s da:s',
 law:'legal:d compliance:d civil:d regaff:b hr:b policy:b credit:s pr:s',
 edu:'teacher:d instr:d ld:d hr:b content:b cs:b civil:b pr:s uxui:s',
 arch:'graphic:d uxui:d gamedesign:b content:b instr:b ae:s pm:s prodeng:s',
 tour:'fo:d ground:d crew:d cs:d sales:b hyg:b storemgr:b mkt:b hr:s content:s'};
const FITM={};Object.keys(FIT_SRC).forEach(f=>{FITM[f]={};FIT_SRC[f].split(' ').forEach(p=>{const [r,l]=p.split(':');FITM[f][r]=l})});
const LVF={d:['🟢',['ตรงสาย','Direct fit'],'good'],b:['🟡',['ข้ามสายได้','Can cross over'],'mid'],s:['🟠',['ต้องเพิ่มทักษะ','Needs new skills'],'cm-s']};
const facOk=(f,m)=>!!(FAC[f]&&(!m||FAC[f].mj[m]));
function fitOf(r,f=S.ob.fac,m=S.ob.major){if(!FAC[f])return null;const mj=m&&FAC[f].mj[m];if(mj&&mj[2].includes(r))return 'd';return FITM[f][r]||null}
function facSkills(f=S.ob.fac,m=S.ob.major){const F=FAC[f];if(!F)return [];const mj=m&&F.mj[m];return [...new Set(F.has.concat(mj?mj[1]:[]))]}
function roleGap(r,f=S.ob.fac,m=S.ob.major){const R=ROLES[r],has=facSkills(f,m);return {have:R.u.filter(k=>has.includes(k)),need:R.u.filter(k=>!has.includes(k)),mo:R.u.filter(k=>!has.includes(k)).reduce((a,k)=>a+SK[k][2],0)}}
const moTxt=n=>n<1?t('ไม่กี่สัปดาห์','a few weeks'):t(`~${n} เดือน`,`~${n} mo`);
const facName=(f=S.ob.fac,m=S.ob.major)=>FAC[f]?x(FAC[f].n)+(m&&FAC[f].mj[m]?` · ${x(FAC[f].mj[m][0])}`:''):'';
const fitBadge=l=>l?`<span class="chip ${LVF[l][2]}">${LVF[l][0]} ${x(LVF[l][1])}</span>`:'';
const rolesIn=g=>Object.keys(ROLES).filter(r=>ROLES[r].g===g);
const groupsIn=w=>Object.keys(GROUPS).filter(g=>GROUPS[g][0]===w);
const worldRoles=w=>groupsIn(w).flatMap(rolesIn);
function roleSal(r){const names=ROLES[r].sal,rows=CO.flatMap(c=>c.salary.filter(s=>!s[5]&&names.includes(s[0][1])).map(s=>[c,s]));if(!rows.length)return null;
 return {lo:Math.min(...rows.map(v=>v[1][1])),mid:Math.round(rows.reduce((a,v)=>a+v[1][2]*v[1][4],0)/rows.reduce((a,v)=>a+v[1][4],0)/500)*500,hi:Math.max(...rows.map(v=>v[1][3])),n:rows.reduce((a,v)=>a+v[1][4],0)}}
function roleCos(r){const R=ROLES[r],ids=new Set(CO.filter(c=>c.salary.some(s=>R.sal.includes(s[0][1]))).map(c=>c.id));JOBS.filter(j=>R.jobs.includes(j.id)).forEach(j=>ids.add(j.co));return CO.filter(c=>ids.has(c.id))}
