/* Maadoo Job · js/parttime.js — quick part-time jobs + rules page. Classic script sharing one global scope; see CLAUDE.md for load order. */
/* ---------- v22: part-time (งานด่วน) ---------- */
const SHOPS={maadoo:{name:['Maadoo (ทีมงานเรา)','Maadoo (our team)'],mk:['🐶','🐶'],hue:'#CFEAFF'},muay:{name:['ร้านก๋วยเตี๋ยวเจ๊หมวย','Jae Muay Noodles'],mk:['🍜','🍜'],hue:'#D9D3FF'},lattelab:{name:['คาเฟ่ ลาเต้แล็บ','Latte Lab Café'],mk:['☕','☕'],hue:'#FFE3B8'}};
const PTRATE={biofresh:[4.6,18,100],riverlight:[4.2,31,96],coralpuff:[4.5,11,100],cloudbun:[4.8,12,100],speedflow:[3.7,54,88],popcorn:[4.0,9,100],bloomy:[4.5,15,100],lattelab:[4.7,6,100],maadoo:[4.9,40,100]};
const PTDAY={today:['วันนี้','Today'],tomorrow:['พรุ่งนี้','Tomorrow'],weekend:['เสาร์–อาทิตย์','Weekend'],online:['ออนไลน์','Online']};
const PTKIND={onsite:['🏢 ที่หน้างาน','🏢 On-site'],online:['🏠 ออนไลน์','🏠 Remote'],piece:['📦 เป็นชิ้นงาน','📦 Per piece']};
const PAYHOW={cash:['เงินสดจบงาน','Cash at end of shift'],transfer7:['โอนภายใน 7 วัน','Bank transfer within 7 days'],weekly:['โอนทุกศุกร์','Transfer every Friday']};
const PT=[
 {id:'p1',co:'biofresh',title:['ผู้ช่วยแล็บ QC · 1 วัน','QC Lab Assistant · 1 day'],kind:'onsite',day:'today',when:['วันนี้ 13:00–18:00','Today 13:00–18:00'],pay:['600 ฿/วัน','600 THB/day'],dist:4.2,need:2,filled:0,close:['ปิดใน 3 ชม.','Closes in 3 h'],boost:'super',req:['เรียนจุลชีวะ/อาหาร ปี 2 ขึ้นไป','Microbiology/food science, year 2+'],how:'cash',desc:['ช่วยเตรียมอาหารเลี้ยงเชื้อ ล้างเครื่องแก้ว และจดผลนับโคโลนี มีพี่ QC ดูแลตลอด','Prepare media, wash glassware and record colony counts, supervised by a QC officer.']},
 {id:'p2',co:'riverlight',title:['พนักงานเสิร์ฟงานเลี้ยง','Banquet server'],kind:'onsite',day:'weekend',when:['ส. 18:00–23:00','Sat 18:00–23:00'],pay:['120 ฿/ชม.','120 THB/h'],dist:12.5,need:6,filled:2,close:null,boost:'urgent',req:['บุคลิกดี สื่อสารภาษาอังกฤษเบื้องต้น','Presentable, basic English'],how:'transfer7',desc:['งานเลี้ยงแต่งงาน 300 ที่ มีชุดยูนิฟอร์มให้ และมีอาหารพนักงาน','A 300-guest wedding. Uniform and staff meal provided.']},
 {id:'p3',co:'cloudbun',title:['ติดป้ายข้อมูลสินค้า (ออนไลน์)','Product data tagging (remote)'],kind:'piece',day:'online',when:['ส่งภายใน 3 วัน','Due within 3 days'],pay:['2 ฿/รายการ','2 THB/item'],dist:null,need:10,filled:4,close:null,boost:'none',req:['มีคอมพิวเตอร์ ใช้ Google Sheets ได้','Own computer, comfortable with Google Sheets'],how:'weekly',desc:['ติดหมวดหมู่สินค้าในระบบ ประมาณ 200–400 รายการ/วัน ทำเวลาไหนก็ได้','Tag product categories, about 200–400 items/day, any time you like.']},
 {id:'p4',shop:'maadoo',title:['ผู้ช่วยตอบคำถาม Maadoo Helper','Maadoo Helper (answer questions)'],kind:'online',day:'online',when:['ตอบเวลาไหนก็ได้','Answer any time'],pay:['20 ฿/คำตอบ + โบนัส','20 THB/answer + bonus'],dist:null,need:20,filled:13,close:null,boost:'none',req:['ยืนยันตัวตน + ป้าย ✓ คนใน · ผ่านแบบทดสอบสั้น ๆ','Verified insider ✓ · pass a short test'],how:'weekly',desc:['ตอบคำถามในบอร์ดพูดคุยในสายที่คุณถนัด ได้โบนัสเมื่อเจ้าของโพสต์กด “มีประโยชน์” คำตอบถูกสุ่มตรวจคุณภาพ','Answer board questions in your field. Bonus when the asker marks your answer helpful. Answers are spot-checked.']},
 {id:'p5',co:'speedflow',title:['แพ็กของช่วงเซล 11.11','Packing crew for the 11.11 sale'],kind:'onsite',day:'tomorrow',when:['พรุ่งนี้ 09:00–18:00','Tomorrow 09:00–18:00'],pay:['550 ฿/วัน + OT','550 THB/day + OT'],dist:6.8,need:30,filled:21,close:['ปิดใน 20 ชม.','Closes in 20 h'],boost:'urgent',req:['ยืนทำงานได้ทั้งวัน','Able to stand all day'],how:'cash',desc:['แพ็กและติดฉลากพัสดุ มีรถรับส่งจาก Airport Link ลาดกระบัง','Pack and label parcels. Shuttle from Airport Link Lat Krabang.']},
 {id:'p6',co:'bloomy',title:['พนักงานแจกสินค้าตัวอย่าง','Product sampling promoter'],kind:'onsite',day:'weekend',when:['อา. 10:00–19:00','Sun 10:00–19:00'],pay:['700 ฿/วัน','700 THB/day'],dist:9.1,need:4,filled:1,close:null,boost:'none',req:['ชอบพูดคุย เข้าใจเรื่องสกินแคร์','Chatty, knows skincare basics'],how:'transfer7',desc:['แนะนำเซรั่มตัวใหม่ที่ห้าง มีอบรมก่อนเริ่มงาน 1 ชม. (ได้ค่าจ้าง)','Introduce a new serum at a mall. 1 h paid training beforehand.']},
 {id:'p7',shop:'lattelab',title:['บาริสต้าพาร์ทไทม์','Part-time barista'],kind:'onsite',day:'weekend',when:['ส.–อา. 08:00–14:00','Sat–Sun 08:00–14:00'],pay:['75 ฿/ชม.','75 THB/h'],dist:1.3,need:1,filled:0,close:null,boost:'none',req:['ไม่มีประสบการณ์ก็ได้ สอนให้','No experience needed, we train'],how:'weekly',desc:['ร้านเล็กหน้ามหาลัย ทำเครื่องดื่มและดูแลหน้าร้าน','Small café by campus. Make drinks and look after the counter.']},
 {id:'p8',shop:'muay',title:['พนักงานร้านก๋วยเตี๋ยว','Noodle shop helper'],kind:'onsite',day:'today',when:['วันนี้ 11:00–15:00','Today 11:00–15:00'],pay:['400 ฿/วัน','400 THB/day'],dist:0.8,need:1,filled:0,close:['ปิดใน 1 ชม.','Closes in 1 h'],boost:'none',req:['คล่องแคล่ว','Quick on your feet'],how:'cash',desc:['ช่วยเสิร์ฟและเก็บโต๊ะช่วงเที่ยง มีข้าวให้กิน','Serve and clear tables over lunch. Meal included.'],newShop:true},
 {id:'p9',co:'coralpuff',title:['ผู้ช่วยแม่บ้านห้องพัก · สุดสัปดาห์','Weekend housekeeping helper'],kind:'onsite',day:'weekend',when:['ส.–อา. 08:00–16:00','Sat–Sun 08:00–16:00'],pay:['550 ฿/วัน','550 THB/day'],dist:5.4,need:3,filled:1,close:null,boost:'none',req:['ไม่มีประสบการณ์ก็ได้ มีพี่สอน','No experience needed, we train you'],how:'transfer7',desc:['ช่วยจัดเตียง เติมของใช้ในห้อง และเตรียมห้องให้พร้อมเช็กอิน มีรถรับส่งจากตัวเมืองหัวหิน อาหารกลางวัน และชุดยูนิฟอร์มให้ฟรี','Make beds, restock amenities and get rooms ready for check-in. Free shuttle from Hua Hin town, lunch and uniform provided.']},
];
const PT_ST=[['📨','ส่งใบสมัครแล้ว','Application sent','#D5E3F6'],['👀','นายจ้างเปิดดูโปรไฟล์แล้ว','Employer viewed your profile','#FFC53D'],['✅','ได้งาน! แชตกับนายจ้างได้เลย','You got the job! Chat with the employer','#1C9D7F'],['⭐','จบงานแล้ว · ให้คะแนนแล้ว','Done · rated','#8494B6']];
const FAKE_APPL=[['Ploy','ปี 4 วิทย์อาหาร','Year 4 food science','#FFE08A',4.7,6],['Tan','ปี 2 จุลชีวะ','Year 2 microbiology','#FFD3E2',0,0],['Nam','ปี 3 เคมี','Year 3 chemistry','#DDF0B5',4.2,2],['Beam','ปี 1 บริหาร','Year 1 business','#C9DBFF',4.9,11]];
const ptOrg=p=>p.co?{name:getCo(p.co).name,mk:getCo(p.co).mk,hue:getCo(p.co).hue,rate:PTRATE[p.co],verified:true,id:p.co}:{...SHOPS[p.shop],rate:PTRATE[p.shop],verified:!p.newShop,id:p.shop};
function ptSorted(list){const w={super:2,urgent:1,none:0};return list.slice().sort((a,b)=>(w[b.boost]-w[a.boost])||((a.dist??99)-(b.dist??99)))}
function ptCard(p){const o=ptOrg(p);const ap=S.ptApps[p.id];const full=p.filled>=p.need;
 return `<button class="ptc ${p.boost!=='none'?'boost':''} ${full?'full':''}" data-pt="${p.id}">
  <div class="ptc-top"><span class="mark sm" style="background:${o.hue}">${x(o.mk)}</span><div class="ptc-t"><b>${esc(x(p.title))}</b><span class="muted">${x(o.name)} · ${o.rate?`★ ${o.rate[0]} (${o.rate[1]})`:t('ร้านใหม่ ยังไม่มีรีวิว','New · no reviews yet')}</span></div>
  ${p.boost==='super'?`<span class="adb">🚨 ${t('ด่วนมาก','Very urgent')} · AD</span>`:p.boost==='urgent'?`<span class="adb">⚡ ${t('ด่วน','Urgent')} · AD</span>`:''}</div>
  <div class="ptc-m"><span class="pay">${x(p.pay)}</span><span>🕘 ${x(p.when)}</span>${p.dist!=null?`<span>📍 ${p.dist} ${t('กม.','km')}</span>`:`<span>${x(PTKIND[p.kind])}</span>`}</div>
  <div class="ptc-m">${full?`<span class="chip">${t('รับครบแล้ว','Filled')}</span>`:`<span class="chip">${t(`ว่าง ${p.need-p.filled} จาก ${p.need} ที่`,`${p.need-p.filled} of ${p.need} spots left`)}</span>`}${p.close&&!full?`<span class="urg">${x(p.close)}</span>`:''}${ap?`<span class="chip ver">${PT_ST[ap.st][0]} ${t(PT_ST[ap.st][1],PT_ST[ap.st][2])}</span>`:''}${p.mine?`<span class="chip mid">${t('โพสต์ของฉัน','My post')}</span>`:''}</div></button>`}
function ptFeed(){const D=S.ptDay;
 let list=PT.filter(p=>D==='all'||p.day===D);list=ptSorted(list);
 const mine=PT.filter(p=>p.mine);
 return `<div class="pt-head"><div><h2 style="font-size:22px">⚡ ${t('งานด่วน พาร์ทไทม์','Quick part-time jobs')}</h2><p class="muted">${t('งานใกล้มหาลัย · สมัคร 1 แตะ · ทุกงานมีคะแนนนายจ้างจากคนเคยทำ','Near campus · one-tap apply · every job shows employer ratings from past workers')}</p></div><button class="btn y" data-ptpost>＋ ${t('โพสต์งานพาร์ทไทม์','Post a part-time job')}</button></div>
 <div class="opts" style="margin-top:12px">${[['all',t('ทั้งหมด','All')],...Object.keys(PTDAY).map(k=>[k,x(PTDAY[k])])].map(([k,n])=>`<button class="opt ${D===k?'on':''}" data-ptday="${k}">${n}</button>`).join('')}</div>
 ${mine.length?`<section class="sec"><div class="sec-h"><h2>${t('โพสต์ของฉัน','My posts')}</h2></div><div class="list">${mine.map(p=>`<div class="li"><b>${esc(x(p.title))}</b><span class="muted">${p.appl.length} ${t('ผู้สมัคร','applicants')} · ${t('รับแล้ว','hired')} ${p.filled}/${p.need}</span><button class="btn grow" data-ptappl="${p.id}">${t('ดูผู้สมัคร','View applicants')}</button></div>`).join('')}</div></section>`:''}
 <div class="grid g2" style="margin-top:14px">${list.length?list.map(ptCard).join(''):`<div class="card empty">${t('ยังไม่มีงานในช่วงนี้','No jobs for this day yet')}</div>`}</div>
 <div class="safe-note">🛡️ ${t('Maadoo ไม่เก็บเงินจากผู้สมัคร และนายจ้างห้ามเก็บเงินผู้สมัครทุกกรณี (ค่าสมัคร ค่าชุด ค่าอบรม) ถ้ามีใครขอเงิน กด “รายงาน” ได้เลย','Applicants never pay. Employers may not charge you anything (application, uniform or training fees). If anyone asks for money, tap “Report”.')} <button class="link" data-go="rules">${t('อ่านกติกา','Read the rules')}</button></div>`}
function ptApply(id){needLogin(()=>{const p=PT.find(v=>v.id===id);S.ptApps[id]={st:0};addPoints(5);S.modal=null;render();toast(t('ส่งใบสมัครแล้ว! +5 แต้ม','Application sent! +5 pts'));
 setTimeout(()=>{if(!S.ptApps[id])return;S.ptApps[id].st=1;pushNotif('👀',`${x(ptOrg(p).name)} เปิดดูโปรไฟล์ของคุณ`,`${x(ptOrg(p).name)} viewed your profile`,['jobs']);if(S.view==='jobs'||S.view==='me')render()},4000);
 setTimeout(()=>{if(!S.ptApps[id])return;S.ptApps[id].st=2;p.filled=Math.min(p.need,p.filled+1);pushNotif('✅',`ได้งาน “${p.title[0]}” แล้ว!`,`You got “${p.title[1]}”!`,['me']);toast(t('🎉 ได้งานแล้ว! ดูรายละเอียดในหน้า “ฉัน”','🎉 You got the job! See “Me”'));if(S.view==='jobs'||S.view==='me')render()},9000)})}
function ptModal(m){const p=PT.find(v=>v.id===m.id);const o=ptOrg(p);const ap=S.ptApps[p.id];const full=p.filled>=p.need;
 return `<div class="modal-h"><span class="mark" style="background:${o.hue};width:52px;height:52px">${x(o.mk)}</span><div><h2>${esc(x(p.title))}</h2><p class="muted">${x(o.name)} ${o.verified?`<span class="chip ver">✓ ${t('ยืนยันธุรกิจแล้ว','Verified business')}</span>`:`<span class="chip mid">${t('ร้านใหม่','New shop')}</span>`}</p></div><button class="x" data-close aria-label="${t('ปิด','Close')}">×</button></div>
 <dl class="kv"><dt>${t('ค่าจ้าง','Pay')}</dt><dd class="pay">${x(p.pay)} · ${x(PAYHOW[p.how])}</dd><dt>${t('เวลา','When')}</dt><dd>${x(p.when)}</dd><dt>${t('รูปแบบ','Type')}</dt><dd>${x(PTKIND[p.kind])}${p.dist!=null?` · ${p.dist} ${t('กม.','km')}`:''}</dd><dt>${t('ต้องมี','Needs')}</dt><dd>${x(p.req)}</dd></dl>
 <p style="font-size:14px;color:var(--ink-2)">${x(p.desc)}</p>
 ${o.rate?`<div class="row" style="gap:6px"><span class="chip ver">😊 ${t(`คนทำพาร์ทไทม์ ${o.rate[1]} คนให้ ★ ${o.rate[0]}`,`${o.rate[1]} part-timers rated ★ ${o.rate[0]}`)}</span><span class="chip">${t('จ่ายตรงเวลา','Paid on time')} ${o.rate[2]}%</span></div>`:`<div class="demo-note">${t('ร้านนี้ยังไม่มีรีวิวจากคนทำพาร์ทไทม์ นัดเจอในที่สาธารณะและอย่าจ่ายเงินใด ๆ','No part-timer reviews yet. Meet in public and never pay anything.')}</div>`}
 ${ap?`<div class="ptstat"><b>${PT_ST[ap.st][0]} ${t(PT_ST[ap.st][1],PT_ST[ap.st][2])}</b><span class="muted">${ap.st<2?t('นายจ้างส่วนใหญ่ตอบภายใน 2 ชม.','Most employers reply within 2 h'):''}</span></div>`:full?`<div class="demo-note">${t('ตำแหน่งนี้รับครบแล้ว','This job is filled')}</div>`:p.mine?`<button class="btn" data-ptappl="${p.id}">${t('ดูผู้สมัคร','View applicants')}</button>`:
 `<div class="appl"><span class="av">${S.user?esc(S.user.name.slice(0,1).toUpperCase()):'🙂'}</span><div><b>${S.user?esc(S.user.name):t('ยังไม่ได้เข้าสู่ระบบ','Not logged in')}${S.user&&S.user.verified?' ✓':''}</b><small>${S.user?t(`สมัครด้วยโปรไฟล์ Maadoo · งานด่วนที่เคยทำ ${Object.values(S.ptApps).filter(a=>a.st>=2).length} งาน`,`Applying with your Maadoo profile · ${Object.values(S.ptApps).filter(a=>a.st>=2).length} past jobs`):t('เข้าสู่ระบบก่อนสมัคร','Log in to apply')}</small></div></div>
  <textarea class="field" id="ptmsg" placeholder="${t('ข้อความถึงนายจ้าง (ไม่บังคับ) เช่น เคยทำงานแล็บมาก่อน','Message to the employer (optional)')}"></textarea>
  <button class="btn y" data-ptapply="${p.id}">⚡ ${t('สมัครเลย','Apply now')}</button>`}
 <div class="row" style="justify-content:space-between"><span class="muted" style="font-size:12px">🛡️ ${t('ห้ามเก็บเงินผู้สมัครทุกกรณี','Employers may never charge applicants')}</span><button class="report" data-ptreport>⚑ ${t('รายงานงานนี้','Report this job')}</button></div>`}
function ptPostModal(){const f=S.ptForm;
 return `<div class="modal-h"><img src="${PUP()}" alt=""><div><h2>${t('โพสต์งานพาร์ทไทม์','Post a part-time job')}</h2><p class="muted">${t('กรอกไม่ถึง 1 นาที','Takes under a minute')}</p></div><button class="x" data-close aria-label="${t('ปิด','Close')}">×</button></div>
 <form id="ptForm" class="grid" style="gap:10px">
  <label class="fl">${t('ชื่องาน','Job title')}<input class="field" id="pf-title" required placeholder="${t('เช่น ผู้ช่วยแล็บ 1 วัน','e.g. Lab assistant for a day')}" value="${esc(f.title)}"></label>
  <div class="two"><label class="fl">${t('รูปแบบ','Type')}<select class="field" id="pf-kind">${Object.keys(PTKIND).map(k=>`<option value="${k}" ${f.kind===k?'selected':''}>${x(PTKIND[k])}</option>`).join('')}</select></label>
  <label class="fl">${t('วัน','Day')}<select class="field" id="pf-day">${Object.keys(PTDAY).map(k=>`<option value="${k}" ${f.day===k?'selected':''}>${x(PTDAY[k])}</option>`).join('')}</select></label></div>
  <label class="fl">${t('เวลา','Time')}<input class="field" id="pf-when" required placeholder="13:00–18:00" value="${esc(f.when)}"></label>
  <div class="two"><label class="fl">${t('ค่าจ้าง (บาท)','Pay (THB)')}<input class="field" id="pf-pay" inputmode="numeric" required value="${esc(f.pay)}"></label>
  <label class="fl">${t('ต่อ','Per')}<select class="field" id="pf-unit"><option value="h" ${f.unit==='h'?'selected':''}>${t('ชั่วโมง','hour')}</option><option value="d" ${f.unit==='d'?'selected':''}>${t('วัน','day')}</option><option value="p" ${f.unit==='p'?'selected':''}>${t('ชิ้น','piece')}</option></select></label></div>
  <div id="pf-wage">${wageMsg(f)}</div>
  <div class="two"><label class="fl">${t('ต้องการกี่คน','Spots')}<input class="field" id="pf-need" type="number" min="1" max="99" value="${esc(f.need)}"></label>
  <label class="fl">${t('จ่ายเงินแบบ','Payment')}<select class="field" id="pf-how">${Object.keys(PAYHOW).map(k=>`<option value="${k}" ${f.how===k?'selected':''}>${x(PAYHOW[k])}</option>`).join('')}</select></label></div>
  <label class="fl">${t('คุณสมบัติ','Requirements')}<input class="field" id="pf-req" placeholder="${t('เช่น เรียนวิทย์ ปี 2 ขึ้นไป','e.g. Science student, year 2+')}" value="${esc(f.req)}"></label>
  <b style="color:var(--navy);margin-top:4px">${t('อยากได้คนเร็วแค่ไหน?','How fast do you need people?')}</b>
  ${[['none','📝',t('โพสต์ปกติ','Standard'),t('ขึ้นในฟีดตามระยะทาง','Shown in the feed by distance')],['urgent','⚡',t('ด่วน · AD','Urgent · AD'),t('ขึ้นบนสุด + ป้าย “ด่วน” 24 ชม.','Pinned to the top + “Urgent” badge for 24 h')],['super','🚨',t('ด่วนมาก · AD','Very urgent · AD'),t('ด่วน + แจ้งเตือนคนที่ตรงเงื่อนไขในรัศมี 10 กม.','Urgent + alerts matching people within 10 km')]].map(b=>`<button type="button" class="bopt ${f.boost===b[0]?'on':''}" data-pfboost="${b[0]}"><span class="ic">${b[1]}</span><span><b>${b[2]}</b><small>${b[3]}</small></span><i class="radio"></i></button>`).join('')}
  <p class="muted" style="font-size:12px">${t('ราคาโปรโมตจะประกาศเร็ว ๆ นี้ · ช่วงเดโมโปรโมตได้ฟรี','Promotion pricing coming soon · free during the demo')}</p>
  <label class="row" style="gap:8px;font-size:13.5px;cursor:pointer"><input type="checkbox" id="pf-ok" ${f.ok?'checked':''} required style="width:18px;height:18px;accent-color:var(--blue)">${t('ยืนยันว่าไม่เก็บเงินผู้สมัคร และข้อมูลงานเป็นความจริง','I won’t charge applicants and this job is real')}</label>
  <button class="btn y">${t('โพสต์งาน','Post job')}</button>
  <p class="demo-note">${t('เดโม: โพสต์ครั้งแรกจริงต้องยืนยันตัวตนหรือธุรกิจก่อน','Demo: real first posts need identity or business verification')}</p></form>`}
function wageMsg(f){const v=+String(f.pay).replace(/[^\d.]/g,'');if(!v||f.unit==='p')return '';
 const hourly=f.unit==='h'?v:v/8;return hourly<50?`<div class="demo-note" style="background:var(--bad-bg);color:var(--bad)">⚠️ ${t('ค่าจ้างนี้อาจต่ำกว่าค่าแรงขั้นต่ำ (ประมาณ 50 บาท/ชม. หรือ 400 บาท/วัน) ตรวจสอบอัตราล่าสุดของจังหวัดก่อนโพสต์','This may be below the minimum wage (about 50 THB/h or 400 THB/day). Check your province’s current rate.')}</div>`:`<div class="muted" style="font-size:12px;color:var(--good)">✓ ${t('ไม่ต่ำกว่าค่าแรงขั้นต่ำโดยประมาณ','At or above the approximate minimum wage')}</div>`}
function ptApplModal(m){const p=PT.find(v=>v.id===m.id);const full=p.filled>=p.need;
 return `<div class="modal-h"><img src="${PUP()}" alt=""><div><h2>${esc(x(p.title))}</h2><p class="muted">${t('รับแล้ว','Hired')} ${p.filled}/${p.need} · ${p.appl.length} ${t('ผู้สมัคร','applicants')}</p></div><button class="x" data-close aria-label="${t('ปิด','Close')}">×</button></div>
 ${p.appl.length?p.appl.map((a,i)=>`<div class="appl"><span class="av" style="background:${a[3]}">${a[0][0]}</span><div><b>${a[0]} · ${S.lang==='en'?a[2]:a[1]}</b><small>${a[4]?`★ ${a[4]} · ${a[5]} ${t('งาน','jobs')}`:t('งานแรก','First job')}</small></div>${a.hired?`<span class="chip ver">✓ ${t('รับแล้ว','Hired')}</span>`:full?'':`<button class="btn" style="padding:6px 14px;margin-left:auto" data-pthire="${p.id}:${i}">${t('รับ','Hire')}</button>`}</div>`).join(''):`<div class="empty">${t('ยังไม่มีผู้สมัคร รอสักครู่นะ','No applicants yet, hang tight')}</div>`}
 ${full?`<div class="demo-note">${t('รับครบแล้ว ระบบปิดประกาศและแจ้งผู้สมัครที่เหลืออย่างสุภาพให้แล้ว','All spots filled. The post is closed and other applicants were notified politely.')}</div>`:''}`}
function ptRateModal(m){const p=PT.find(v=>v.id===m.id);const o=ptOrg(p);const r=S.ptRate;
 return `<div class="modal-h"><span class="mark" style="background:${o.hue};width:52px;height:52px">${x(o.mk)}</span><div><h2>${t('ให้คะแนนนายจ้าง','Rate the employer')}</h2><p class="muted">${x(o.name)} · ${esc(x(p.title))}</p></div><button class="x" data-close aria-label="${t('ปิด','Close')}">×</button></div>
 <div class="starsel" style="text-align:center">${[1,2,3,4,5].map(i=>`<button type="button" class="${r.s>=i?'on':''}" data-ptstar="${i}" aria-label="${i}">★</button>`).join('')}</div>
 <div class="opts" style="justify-content:center">${[['ontime',['จ่ายตรงเวลา','Paid on time']],['asdesc',['งานตรงปก','Job as described']],['kind',['ดูแลดี','Treated well']],['over',['ทำงานเกินเวลา','Worked overtime']],['late',['จ่ายช้า','Paid late']]].map(g=>`<button type="button" class="opt sm ${r.tags[g[0]]?'on':''}" data-pttag="${g[0]}">${x(g[1])}</button>`).join('')}</div>
 <p class="muted" style="text-align:center">${t('คะแนนนี้ขึ้นในหน้าบริษัท ส่วน “พาร์ทไทม์” ช่วยให้คนถัดไปตัดสินใจ','Shown on the company page under “Part-time” to help the next person')}</p>
 <button class="btn y" data-ptratesend="${p.id}" ${r.s?'':'disabled'}>${t('ส่งคะแนน +3 แต้ม','Submit +3 pts')}</button>`}

function rules(){return `<div class="rules" style="margin-top:8px"><h1 style="font-size:28px">${t('แนวทางรีวิวและความเป็นส่วนตัว','Review guidelines & privacy')}</h1>
 <div class="card"><h2>⚡ ${t('งานพาร์ทไทม์ปลอดภัย','Safe part-time work')}</h2><ul><li>${t('นายจ้างห้ามเก็บเงินผู้สมัครทุกกรณี เช่น ค่าสมัคร ค่าชุด ค่าอบรม','Employers may never charge applicants: no application, uniform or training fees')}</li><li>${t('ระวังงานที่ให้ “กดไลก์รับเงิน” หรือ “โอนก่อนได้งาน” นี่คือมิจฉาชีพ','Beware of “like posts for cash” or “pay first to get the job” — these are scams')}</li><li>${t('นายจ้างต้องยืนยันตัวตนหรือธุรกิจก่อนโพสต์ และระบบเตือนเมื่อค่าจ้างต่ำกว่าค่าแรงขั้นต่ำ','Employers verify identity or business before posting; low wages trigger a warning')}</li><li>${t('ให้คะแนนกันสองฝั่งหลังจบงาน เบี้ยวงาน 2 ครั้งจะถูกพักสิทธิ์ 14 วัน','Both sides rate each other; two no-shows pause applying for 14 days')}</li></ul></div>
 <div class="card"><h2>${t('เขียนรีวิวอย่างไรให้ผ่าน','How to write a review that gets published')}</h2><ul><li>${t('เล่าจากประสบการณ์ตรงของตัวเองภายใน 3 ปีที่ผ่านมา','Share your own experience from the past 3 years')}</li><li>${t('ห้ามระบุชื่อ-นามสกุลบุคคล ให้ใช้ตำแหน่งแทน','Don’t name individuals; use job titles instead')}</li><li>${t('ห้ามคำหยาบ ข้อมูลลับทางการค้า หรือข้อมูลส่วนตัวของผู้อื่น','No profanity, trade secrets or other people’s personal data')}</li><li>${t('วิจารณ์ได้ แต่ต้องเป็นข้อเท็จจริงหรือความเห็นที่สุจริต','Criticism is fine if it’s factual or an honest opinion')}</li></ul></div>
 <div class="card"><h2>${t('รีวิวถูกตรวจอย่างไร','How reviews are moderated')}</h2><ul><li>${t('ทุกรีวิวผ่านระบบกรองอัตโนมัติและทีมงานก่อนเผยแพร่','Every review passes automated checks and a human moderator')}</li><li>${t('ใครก็กด “⚑ รายงาน” ได้ ทีมตรวจภายใน 48 ชั่วโมง','Anyone can tap “⚑ Report”; we respond within 48 hours')}</li><li>${t('บริษัทตอบกลับได้ แต่จ่ายเงินเพื่อลบรีวิวไม่ได้','Companies can reply, but can’t pay to remove reviews')}</li></ul></div>
 <div class="card"><h2>${t('ความเป็นส่วนตัว (PDPA)','Privacy (PDPA)')}</h2><ul><li>${t('ไม่แสดงชื่อผู้รีวิว วันที่แสดงเป็นไตรมาส','Reviewer names are never shown; dates are shown by quarter')}</li><li>${t('ตำแหน่งที่มีคนน้อยกว่า 3 คนจะไม่แสดงเงินเดือน','Salaries are hidden for roles with fewer than 3 reports')}</li><li>${t('อีเมลที่ใช้ยืนยันตัวตนไม่ถูกส่งให้บริษัท','Verification emails are never shared with employers')}</li><li>${t('ขอลบบัญชีและข้อมูลทั้งหมดได้ทุกเมื่อ','You can delete your account and data at any time')}</li></ul></div>
 <p class="muted">${t('เนื้อหานี้เป็นตัวอย่างสำหรับเดโม ก่อนเปิดใช้จริงควรให้นักกฎหมายตรวจ','Sample text for the demo. Have a lawyer review it before launch.')}</p></div>`}

